### PR TITLE
Clean WeakConcurrentMap from background thread

### PR DESCRIPTION
**Pull request by laurit**
Currently our `WeakConcurrentMap` is only cleaned of stale entries when it is accessed. There is an option to clean from a background thread, but this creates a separate thread for every map. This pr introduces a single background thread that cleans all maps.
I removed the option to create a thread per map as we don't use it, if there is interest I could attempt to find a way to add it back.

### CODE REVIEW

**Comment by trask** [comment]
> Currently our `WeakConcurrentMap` is only cleaned of stale entries when it is accessed.

can you share thoughts / theories on why this is not enough? thx

**Comment by laurit** [comment]
> > Currently our `WeakConcurrentMap` is only cleaned of stale entries when it is accessed.
> 
> can you share thoughts / theories on why this is not enough? thx

This map keeps weak reference to keys and strong reference to values. Keys are collected automatically but values are cleared only when map is accessed. This does not guarantee that values are cleared in timely fashion or that they are cleared at all. Using a background thread allows for clearing values immediately after the key is collected.
This change is motivated by the recent question on slack about why we aren't using the cleaner threads. I am not aware of any issues that would require us to use a background thread, this just feels like a potential improvement to me.

**Review by trask — APPROVED** [review]
sorry about the long delay, it was not so scary after digging in a bit 👍

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by trask** [comment]
thx @laurit ❤️

**Comment by lenin-jaganathan** [comment]
@mateuszrzeszutek / @trask We do Observe this particular issue causing a huge memory leak in some of our microservices. I am glad this is caught and fixed, but will this fix be backported to earlier versions? I am not aware of the version support process for OTEL agents. But just being curious about what happens to the customers on older versions.

**Comment by mateuszrzeszutek** [comment]
Hey @lenin-jaganathan ,
No, we won't backport it. We only support the latest minor version; and we recommend using the latest minor version.

**Pull request merged**
