### PR TITLE
Migrate grpc instrumentation to InstrumentationTracer/Span

### PR DESCRIPTION
**Pull request by tylerbenson**
I decided to try migrating grpc since it's less standard, and found there were some incongruences, but nothing I wasn't able to work through.  I think for more standard things like http clients/servers it will be smoother. I'll try one of those next.

### CODE REVIEW

**Comment by trask** [comment]
Thanks! @iNikem is also making progress on this in #469. For now, in #469, there's no "instrumentation span", and i think the proposal is to directly use the [typed spans](https://github.com/open-telemetry/opentelemetry-specification/issues/547) from @thisthat when they are available.

Do you have thoughts on advantages/disadvantages of having both "instrumentation tracer" and "instrumentation span" vs the approach in #469 where the span lifecycle stuff is all in the "instrumentation tracer"?

**Comment by iNikem** [comment]
This approach is very different from mine :)

My idea, that I tried to pursue in #469 and #466, is to have the following separation of concerns:

- Typed/Semantic spans define the "shape" of a particular span, like http server or db client. This means that they expose the API for specific attributes as defined by semantic convention. And maybe some helper methods such as `setHttpAttributes(host, port, target, fragment)`. But they are totally independent from the specific _library_. E.g. there is `DbClientSpan`, but no `JdbcClientSpan`. As these classes will most probably be generated directly from specification (see open-telemetry/opentelemetry-specification#547), they really cannot be library specific. Thus, IMO, they cannot have methods such as https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/477/files#diff-5b6203e2b670f6f7d028b395223c2afdR41
- Typed/Semantic tracers are abstract superclasses that know the general "flow", how to create semantic spans and where to extract the required data. E.g. `HttpServerSpan` knows such things as `request` and `response` and `url`. Concrete subclasses, such as `GrizzlyHttpServerSpan` knows the specific implementation of `request` and `response` and can extract specific attribute values from them. Tracers expose "lifecycle" API methods, such as `startSpan` and `endExceptionally`.
- Instrumentation/Advice knows the instrumented library, what classes to instrument and where to inject calls to tracers' lifecycle methods.

**Comment by trask** [comment]
> E.g. `HttpServerSpan` knows such things as request and response and url. Concrete subclasses, such as `GrizzlyHttpServerSpan` knows the specific implementation of request and response and can extract specific attribute values from them

@iNikem, I assume you mean HttpServer**Tracer** and GrizzlyHttpServer**Tracer** in this example?

**Comment by iNikem** [comment]
> > E.g. `HttpServerSpan` knows such things as request and response and url. Concrete subclasses, such as `GrizzlyHttpServerSpan` knows the specific implementation of request and response and can extract specific attribute values from them
> 
> @iNikem, I assume you mean HttpServer**Tracer** and GrizzlyHttpServer**Tracer** in this example?

Yes, of course. Sorry for the confusion

**Comment by trask** [comment]
The approaches don't seem that different to me (at least as a high level). The approach in this PR spreads the instrumentation-specific work across two classes "instrumentation tracer" and "instrumentation span", while #469 puts all instrumentation-specific work into one class "instrumentation tracer".

Both approaches would use the semantic spans from @thisthat when available.

I think it makes sense to go forward with #469 as a first step, and then see how things look once we have the semantic spans, and after that I think it will be clearer if/how we might benefit further from splitting out "instrumentation spans".

**Comment by iNikem** [comment]
I don't quite see how this PR can accommodate generated semantic spans. They cannot possible do "instrumentation-specific work", can they?

**Comment by trask** [comment]
> I don't quite see how this PR can accommodate generated semantic spans. They cannot possible do "instrumentation-specific work", can they?

The approach in this PR is to have "instrumentation-specific spans" in addition to (e.g. wrapping) the generated semantic spans.

**Comment by iNikem** [comment]
Aah, now I understand your point, thanks for the patience :)

**Comment by tylerbenson** [comment]
Ok, I'm a bit confused.  Should I close this PR or spend some time trying to fix the tests?

**Comment by trask** [comment]
I suggest that we start with the approach in #469, and then layer in semantic spans from @thisthat once they are available, and then after that, we revisit whether we want to add "instrumentation spans" concept on top of semantic spans (which to me is the main difference between the approaches in this PR and #469).

If this seems like a reasonable path forward, it would be great to rebase this PR and align it with #469.

We can definitely discuss on Thu also, I've added this topic to [the agenda](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw).

**Comment by tylerbenson** [comment]
I'll go ahead and close this PR for now.  We can revisit when we've made further progress on the API.

**Pull request closed without merging**
