### PR TITLE
fix bug: get return type in a wrong way for method instrumentation

### PR DESCRIPTION
**Pull request by darcydai**
After testing, @Advice.Origin("#r") can only insert a string type parameter from the constant pool.
@Advice.Origin("#r") Class<?> returnType: returnType is current class for method

### CODE REVIEW

**Comment by laurit** [comment]
@darcydai could you add a test for this?

**Comment by darcydai** [comment]
> @darcydai could you add a test for this?

yes, later

**Comment by darcydai** [comment]
> @darcydai could you add a test for this?

it is hard to approve `@Advice.Origin("#r") Class<?> returnType` is the wrong way to get the return type by a test case,because this is `bytebuddy` feature.
I wrote a test case that use `@Advice.Origin("#r") Class<?> returnType` can not pass.

**Comment by laurit** [comment]
@darcydai I created a pull request https://github.com/darcydai/opentelemetry-java-instrumentation/pull/1 for your pull request. I moved the new test into a separate method and instead of figuring out from span length checked directly whether span was still running after the method completed. WDYT?

**Comment by laurit** [comment]
@darcydai I created a pull request https://github.com/darcydai/opentelemetry-java-instrumentation/pull/1 for your pull request. I moved the new test into a separate method and instead of figuring out from span length checked directly whether span was still running after the method completed. WDYT?

**Review by laurit — APPROVED** [review]

**Review by trask — APPROVED** [review]
thx!

**Pull request merged**
