### PR TITLE
Type annotation placement

### PR DESCRIPTION
**Pull request by MartinDai**
switch annotation `org.checkerframework.checker.nullness.qual.Nullable` to `javax.annotation.Nullable` #4291

### CODE REVIEW

**Review by trask — APPROVED** [review]
thx @MartinDai!

**Comment by trask** [comment]
Going ahead and merging to avoid conflicts

**Comment by iNikem** [comment]
Do I miss something? This PR changes which annotation we use, but it did not change the annotation location, right? We still have to do that somehow, right?

**Comment by mateuszrzeszutek** [comment]
The annotation placement seems to have been changed though
```java
  @Nullable
  protected Long requestContentLength(
```
Not sure if in all places though

**Pull request merged**
