### PR TITLE
Retry smoke tests

### PR DESCRIPTION
**Pull request by trask**
Mitigates #2820 and #2785. I propose to also close them if this works, and there are no objections.

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]

**Comment by laurit** [comment]
These tests are already retried. From https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2820 https://scans.gradle.com/s/npcmvqdj4e3a2/tests test is executed 5 times and still fails. Here is another scan where it fails the same way https://scans.gradle.com/s/6cc22rgkbl7pi/tests In both of these the failing server is 13.0.0.Final JDK 8 which makes me wonder whether this is an actual bug. It looks like no traces are received, but as there is very little info it seems to be impossible to tell what actually went wrong. Perhaps it would be better to add a bit more logging to these, `LoggingSpanExporter` output that is present in regular tests could tell us whether spans were created at all. To be honest I don't think we can get these tests to run stably by adding more retries, it might be better to temporarily remove the retries at least from the nightly build so we could get a better idea about which tests are flaky so we could fix them or add enough logging to reveal the cause of failures. If this does not work out well then we can always add the retry back. Initially we could keep retry for pr builds so that it wouldn't disrupt people. With the current retries we don't really know how likely this test is to fail, it might always require 3 retries to pass (if it were so then debugging it would be a lot easier). Also it might be good idea to make nightly build always run tests and not use the cached results.

**Comment by trask** [comment]
> These tests are already retried.

When they are re-tried, does it restart the containers? I'm wondering if retrying via the github action will have a better chance of succeeding since it should restart more stuff(?)

> Also it might be good idea to make nightly build always run tests and not use the cached results.

👍👍

**Comment by laurit** [comment]
From the test output it looks like it restarts the server. I think it reruns the whole test class, so when one server version fails all will be rerun. I have no idea whether retry from github action would help. I guess it restarts the gradle process, idk whether that helps.

**Comment by trask** [comment]
Closing this in favor of the work @laurit is doing to find the root cause of the failures

**Pull request closed without merging**
