### PR TITLE
Hopefully fix flaky spring-rmi test

### PR DESCRIPTION
**Pull request by laurit**

### CODE REVIEW

**Review by trask — APPROVED** [review]
were you still seeing flakes after #5164?

**Comment by laurit** [comment]
@trask I didn't notice that pr. If I remember correctly we had something similar going on with regular rmi test which was fixed by adding this jvm argument https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2738

**Comment by trask** [comment]
I just got clean runs after merging #5164 into #5165 and #5160. I'm good with either waiting to see if there is additional flakiness, or proactively merging this given we have similar config for rmi tests.

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by mateuszrzeszutek** [comment]
I think we should probably merge this one too, there may be more than 1 issue here.

**Pull request merged**
