### PR TITLE
Don't wrap request/response in Jetty

### LINKED ISSUE #1096: ClassCastException for v3_0.CountingHttpServletResponse
Hello, running the Java agent (v0.7.1) with a Java 1.8 app results in the following error with `jetty.server.Response`: 

```
[2020-08-24 20:13:46,734] [qtp1474515510-53] WARN server.HttpChannel: Could not send response error 500: java.lang.ClassCastException: io.opentelemetry.auto.instrumentation.servlet.v3_0.CountingHttpServletResponse cannot be cast to org.eclipse.jetty.server.Response
[2020-08-24 20:13:48,671] [qtp1474515510-121] WARN server.HttpChannel: /sso/health
java.lang.ClassCastException: io.opentelemetry.auto.instrumentation.servlet.v3_0.CountingHttpServletResponse cannot be cast to org.eclipse.jetty.server.Response
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:104) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479) ~[jetty-servlet-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
...
...
[REDACTED]
```

I can provide the relevant Pom files after scrubbing if you'd like to know versions for specific libraries, but Jetty seems to be `v9.1.2` which should be supported according to the list of frameworks in the main [README](https://github.com/open-telemetry/opentelemetry-java-instrumentation#supported-java-libraries-and-frameworks).

Is there any guidance on how best to debug this or does this seem like a potential bug in the intstrumentation ? 

**To Note:** This DOES break the application due to the ClassCastException and is not a graceful error (even though in the logs it says WARN)

### PR DESCRIPTION
**Pull request by iNikem**
Fixes #1096

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Thanks!

**Review by trask — APPROVED** [review]
is it easy to write a test for the problem, so we don't accidentally wrap jetty response in the future?

**Comment by iNikem** [comment]
I will see what I can do

**Comment by iNikem** [comment]
@trask Added test and verified that it fails in main branch

**Pull request merged**
