### PR TITLE
Disable jar task in javaagent module

### PR DESCRIPTION
**Pull request by iNikem**
Are there any reasons why we cannot do this?

### CODE REVIEW

**Comment by mateuszrzeszutek** [comment]
I think there were come complications with the artifacts produced by the `shadowJar` plugin, and leaving the `jar` task seemingly fixed them - if I remember correctly the no-classifier jar disappeared when you turned off `jar` and tried to publish to maven.

**Comment by iNikem** [comment]
> I think there were come complications with the artifacts produced by the `shadowJar` plugin, and leaving the `jar` task seemingly fixed them - if I remember correctly the no-classifier jar disappeared when you turned off `jar` and tried to publish to maven.

A, what this build failure means... I will look into that, thanks! :)

**Comment by iNikem** [comment]
Well... I think we have some sort of a pickle here...

First, I think it is wrong that we apply `java-library` plugin to `javaagent` module. This also leads to us trying to publish "common" jar from that module. I don't think we should do it. We should publish only two shadow jars from it.

Second, we actually never asked gradle specifically to publish our shadow jar. I think it worked accidentally, because we overwrite the result of `jar` file with a shadow jar without classifier.

**Comment by trask** [comment]
It's nice to see the `examples` build catching jar publishing problems now prior to releasing 😅

**Review by trask — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]

**Pull request merged**
