### PR TITLE
add LoggingMetricExporterAutoConfiguration to spring factories

### PR DESCRIPTION
**Pull request by zeitlinger**
it was forgotten before

### CODE REVIEW

**Review by laurit — APPROVED** [review]

**Review by jeanbisutti — COMMENTED** [review]
It may be useful to add automatic tests as it's done for `LoggingSpanExporter`

**Comment by zeitlinger** [comment]
> It may be useful to add automatic tests as it's done for `LoggingSpanExporter`

adding external tests is quite an effort: I've done that for various spring configurations and versions in a [distro](https://github.com/grafana/grafana-opentelemetry-java/tree/main/examples) - and I'm happy to contribute that - but it's quite big.

**Comment by jeanbisutti** [comment]
> > It may be useful to add automatic tests as it's done for `LoggingSpanExporter`
> 
> adding external tests is quite an effort: I've done that for various spring configurations and versions in a [distro](https://github.com/grafana/grafana-opentelemetry-java/tree/main/examples) - and I'm happy to contribute that - but it's quite big.

There are several tests verifying the presence or absence of the `LoggingSpanExporter` bean, for different configurations. See [this test](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/35b143a7ac16384fc914e160374127cfab941d88/instrumentation/spring/spring-boot-autoconfigure/src/test/java/io/opentelemetry/instrumentation/spring/autoconfigure/exporters/SpanExporterAutoConfigurationTest.java#L34) for example. You could do the same thing for the `LoggingMetricExporter` bean.

**Comment by jeanbisutti** [comment]
It would be great to document this feature on https://opentelemetry.io/ after the next release

**Comment by zeitlinger** [comment]
> > > It may be useful to add automatic tests as it's done for `LoggingSpanExporter`
> > 
> > 
> > adding external tests is quite an effort: I've done that for various spring configurations and versions in a [distro](https://github.com/grafana/grafana-opentelemetry-java/tree/main/examples) - and I'm happy to contribute that - but it's quite big.
> 
> There are several tests verifying the presence or absence of the `LoggingSpanExporter` bean, for different configurations. See [this test](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/35b143a7ac16384fc914e160374127cfab941d88/instrumentation/spring/spring-boot-autoconfigure/src/test/java/io/opentelemetry/instrumentation/spring/autoconfigure/exporters/SpanExporterAutoConfigurationTest.java#L34) for example. You could do the same thing for the `LoggingMetricExporter` bean.

This PR is changing the spring factories, which are not used in the test you mentioned IIUC.

**Comment by jeanbisutti** [comment]
My point was about the tests on the autoconfiguration creating the `LoggingMetricExporter` bean.

The test class for this autoconfiguration in fact already exists (`LoggingMetricExporterAutoConfigurationTest`).

**Review by jeanbisutti — APPROVED** [review]

**Pull request merged**
