### PR TITLE
Update the OpenTelemetry SDK version to 1.35.0 and remove jaeger exporter

### PR DESCRIPTION
**Pull request by laurit**
Backport of https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10455 and https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10241

### CODE REVIEW

**Comment by trask** [comment]
is removing jaeger exporter necessary? would be nice not to do that in a patch release if we don't have to

**Comment by laurit** [comment]
> is removing jaeger exporter necessary? would be nice not to do that in a patch release if we don't have to

Jaeger exporter was removed from sdk. That leaves us the following options
- remove jaeger
- not update sdk
- include the latest jaeger exporter and hope that it works with the latest sdk

**Comment by trask** [comment]
I think my preference would be to not update the SDK in that case.

@jack-berg @jkwatson any thoughts? thanks

**Comment by jkwatson** [comment]
> I think my preference would be to not update the SDK in that case.
> 
> @jack-berg @jkwatson any thoughts? thanks

No opinion from me. I don't use the agent, and now I don't use the Jaeger exporters, either. ;)

**Comment by trask** [comment]
another option would be to bump the version to `1.36.0` (creating a new `release/v1.36.x` branch)

**Comment by jack-berg** [comment]
Creating new 1.x release branches which mirror opentelemetry-java releases is interesting.. 

I'm also open to publishing patch releases for 1.34.x for security vulnerabilities until instrumentation's support for 1.x ends. I recall that semconv requires >= 6 months of support. Is there a specific support time period in mind for 1.x?

**Comment by trask** [comment]
> another option would be to bump the version to `1.36.0` (creating a new `release/v1.36.x` branch)

oops, I meant `1.33.0` (creating a new `release/v1.33.x` branch)

**Comment by trask** [comment]
> I recall that semconv requires >= 6 months of support. Is there a specific support time period in mind for 1.x?

I think we're open to security patching 1.x for longer than 6 months if there's demand

**Review by trask — APPROVED** [review]

**Comment by trask** [comment]
I re-targeted this to the new `release/v1.33.x` branch

**Pull request merged**
