### PR TITLE
Try CiMate

### PR DESCRIPTION
**Pull request by iNikem**
This PR adds CiMate integration.

CiMate is an incubating project @bsideup providing test report aggregation. For now this will add a status link to PRs which points to easy to read test report UI. CiMate currently does not have over the time aggregation view which would help to detect flaky tests, but there are such plans.

Let us try it out if it will make our life easier :)

Partially addresses #882

### CODE REVIEW

**Comment by bsideup** [comment]
Hey! One of ciMate's creators here. We're in contact with GitHub's support on why the check isn't appearing. It seems to be some exceptional case (on GH's side, since `check_suite` isn't being sent to ciMate's API), probably because @iNikem used to have an app installed on his fork.

But the service itself seems to be working, here is the aggregation for the last commit on this PR:
https://app.cimate.io/mz1jo49x/c6117a4 (the format in `https://app.cimate.io/$projectId/$commitPrefix`)

**Comment by bsideup** [comment]
While waiting for GitHub's response, I will try to analyze why some test suites are marked as "failed".
As @iNikem suggested, it may be that they are being re-run.

Despite all of said issues, I hope ciMate will bring at least some help when it comes to analysing CI test failures, and we have a lot of ideas in our roadmap that should make it easier to pinpoint the issue and get more sense out of the test results.
I kinda like how it matches OT's goal of getting the most out of otherwise raw traces 😊

**Comment by trask** [comment]
thx for the help @bsideup!

**Comment by bsideup** [comment]
FTR as a workaround, I enabled the GitHub Check. It requires an additional click, but at least should work with PRs.

**Pull request merged**
