### PR TITLE
Enable strict context check in tests by default

### PR DESCRIPTION
**Pull request by trask**
Based on @iNikem's https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3811#issuecomment-896628035

### CODE REVIEW

**Comment by trask** [comment]
will wait until after 1.5.0 to mark this ready for review, since it will likely introduce some sporadic failures until we apply `enableStrictContext=false` to them

**Comment by trask** [comment]
Got a green build.. planning to re-run several times to try to iron out other sporadic failures this may introduce..

**Review by mateuszrzeszutek — APPROVED** [review]
WDYT about creating a tracking issue for all those modules that have this check disabled?

**Review by laurit — APPROVED** [review]

**Comment by trask** [comment]
> WDYT about creating a tracking issue for all those modules that have this check disabled?

👍 created #3916

**Pull request merged**
