### PR TITLE
Add `classLoaderOptimization()` to `@WithSpan` instrumentations

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Comment by laurit** [comment]
Usually we don't add `classLoaderOptimization` to matchers that match based on only the current class only. Did you measure these taking excessive time?

**Comment by mateuszrzeszutek** [comment]
> Usually we don't add `classLoaderOptimization` to matchers that match based on only the current class only. Did you measure these taking excessive time?

Nah, I admit I didn't.

Don't we usually add `classLoaderOptimization` to matchers that match more than just the class name? Anything that requires parsing out the bytecode.

**Comment by trask** [comment]
> Don't we usually add `classLoaderOptimization` to matchers that match more than just the class name? Anything that requires parsing out the bytecode.

this is what I thought too

**Comment by laurit** [comment]
Tested this with starting liferay. Wrapped the `ElementMatcher` used in `classLoaderOptimization` and `typeMatcher` and measured how long it took. Without `classLoaderOptimization`
```
WithSpanInstrumentation2-typeMatcher count=46016, time=1274ms
WithSpanInstrumentation1-typeMatcher count=46006, time=231ms
```
One matcher taking longer is probably because the first one called has to parse the class. With `classLoaderOptimization`
```
WithSpanInstrumentation1-classLoaderOptimization count=46026, time=19ms
WithSpanInstrumentation2-classLoaderOptimization count=46036, time=19ms
```
So this is definitely an improvement.
Would it make more sense to use `classLoaderMatcher` in instrumentation module instead of `classLoaderOptimization`?

**Comment by mateuszrzeszutek** [comment]
Thanks for checking this @laurit ! 

> Would it make more sense to use `classLoaderMatcher` in instrumentation module instead of `classLoaderOptimization`?

The result of both of these methods gets `and`ed anyway, so the difference between the two is purely semantic.

**Pull request merged**
