### PR TITLE
Pass context to content length http metrics meters

### PR DESCRIPTION
**Pull request by anuragagarwal561994**
Closes https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7505

### CODE REVIEW

**Comment by anuragagarwal561994** [comment]
@trask can you check this issue, I was trying to create a custom view using the baggage api to pass additional attributes and discovered the baggage not available in content length metrics.

**Review by trask — APPROVED** [review]
👍

**Review by mateuszrzeszutek — COMMENTED** [review]
@anuragagarwal561994 can you add some verifications to the existing tests?
E.g. like https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api-semconv/src/test/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpServerMetricsTest.java#L94

**Comment by anuragagarwal561994** [comment]
@mateuszrzeszutek done, I have added a check to check examplar from context.

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by mateuszrzeszutek** [comment]
@opentelemetrybot spotless

**Comment by trask** [comment]
wait.. this worked??? 🎉

image

**Comment by trask** [comment]
oh but it doesn't kick off the status checks due to using GITHUB_TOKEN

**Comment by anuragagarwal561994** [comment]
@trask is something to be done here from my side?

**Comment by trask** [comment]
> @trask is something to be done here from my side?

nope, thx for the ping, now merged!

**Pull request merged**
