### PR TITLE
Remove latestDepTest from rxjava-1.0 which doesn't have any test sour…

### PR DESCRIPTION
**Pull request by anuraaga**
…ces.

### CODE REVIEW

**Comment by iNikem** [comment]
Probably more correct solution is to add tests? :)

**Comment by anuraaga** [comment]
Yeah should have filed an issue about that! 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1033

I think this change still stands separately.

**Comment by iNikem** [comment]
Sorry for nitpicking, but if we solve #1033, we will add `latestDepTest` back, no?

**Comment by anuraaga** [comment]
Yeah, though it might be a different form, just `library` :) Let's solve that in #1033 not here, right?

**Pull request merged**
