### PR TITLE
Add experimental span attribute job.system

### PR DESCRIPTION
**Pull request by trask**
Introduces experimental `job.system` span attribute from https://github.com/open-telemetry/opentelemetry-specification/pull/1582

[motivation: we're mapping scheduled jobs to "top-level" operations (similar to SERVER/CONSUMER spans, but scheduled jobs are INTERNAL), and I need a way to identify them that doesn't involve checking the InstrumentationScope, since the scope isn't available in samplers]

### CODE REVIEW

**Review by mateuszrzeszutek — COMMENTED** [review]
We should probably include Spring Batch too.

One more question: this kinda duplicates the instrumentation/scope name, is that not usable for you?

**Comment by trask** [comment]
> We should probably include Spring Batch too.

will do

> One more question: this kinda duplicates the instrumentation/scope name, is that not usable for you?

oh ya, I should have mentioned, I want to detect now in a sampler, which doesn't have scope (yet) 😞

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by julealgon** [comment]
Question on this: shouldn't it be a resource attribute instead of a span attribute? 

We already have these today for identifying the web Engine:
- https://opentelemetry.io/docs/specs/semconv/resource/webengine/

With attributes:
- `webengine.description`
- `webengine.name`
- `webengine.version`

It feels to me like the same structure would apply to a job scheduler/runner.

**Comment by trask** [comment]
hi @julealgon! I don't see `webengine.*` attributes in this PR, can you clarify the relation to this PR, or even better probably open a new issues with all of the context? thanks

**Comment by julealgon** [comment]
> hi @julealgon! I don't see `webengine.*` attributes in this PR, can you clarify the relation to this PR, or even better probably open a new issues with all of the context? thanks

Hi @trask . Those `webengine.*` attributes are not in the PR at all. I just brought them up because they were standardized in OTEL Semantic Conventions as _resource attributes_ and, to me, they model something _very_ similar to `job.system`, but `job.system` was added as a span-level attribute here in the instrumentation instead.

I was arguing/asking whether it would not have made more sense to have `job.system` in a "Job resource" instead (in my mind it would).

**Comment by laurit** [comment]
@julealgon the scheduling library, such as quarts, is but a small part of the application, but the resource is shared for all telemetry from the same jvm.

**Pull request merged**
