### PR TITLE
[WIP] Generating client span for SCG while using opentelemetry-spring-boot-starter

### PR DESCRIPTION
**Pull request by 123liuziming**
related to issue https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10648

### CODE REVIEW

**Comment by zeitlinger** [comment]
please add a unit test

**Comment by 123liuziming** [comment]
> please add a unit test

Yes, I am working on that！

**Comment by 123liuziming** [comment]
I've tried to use   [micrometer-tracing](https://projectreactor.io/docs/netty/release/reference/index.html#_tracing_4) in Reactor Netty to add client span for Spring Cloud Gateway's HttpClient. The Webflux's server span ends before the  Reactor Netty's HTTP span

The Webflux span is the parent span of Reactor Netty's hostname resolution span.

**Comment by 123liuziming** [comment]
Maybe we need to enhance each `reactor.netty.http.client.HttpClient` bean in Spring Context.

**Pull request closed without merging**
