### PR TITLE
rename the root project to match the current project name

### PR DESCRIPTION
**Pull request by jkwatson**

### CODE REVIEW

**Comment by jkwatson** [comment]
CI is failing...not sure if something in the circle setup is tied to the root project name? Speaking of which, in the circle config.yml, there's still a bunch of reference to `dd-trace-java`, which should really be cleaned up.

**Comment by iNikem** [comment]
> CI is failing...not sure if something in the circle setup is tied to the root project name? Speaking of which, in the circle config.yml, there's still a bunch of reference to `dd-trace-java`, which should really be cleaned up.

Does project build successfully locally on your machine?

**Comment by jkwatson** [comment]
It fails the same way for me locally... isn't gradle the best?  ;)

**Comment by jkwatson** [comment]
The issue is here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/623226641a18e87b6bedfd5ddec6150ede854e6e/settings.gradle#L174

I'll rename the root gradle file to match.

**Comment by jkwatson** [comment]
Even better, I've renamed the root build gradle to be the gradle  standard, making it less surprsing to new contributors. :)

**Pull request merged**
