### PR TITLE
Rename package for Tracers

### LINKED ISSUE #912: Follow up tasks from PR #893
- [x] // Copy of HttpServerDecorator url handling (extract a method) in httpclienttracer
- [x] make spanNameForRequest protected in HttpClientTracer.java
- [x] update the package using tracer not decorator
- [x] clean up common code between client and server tracers
- [x] consider a new class for static methods extracted from BaseTracer
~~- [x] remove port and url in UrlInstrumentation. this requires updating tests. #1039.~~
- [x] rename and update unit tests under :instrumentation:agent-bootstrap:test
- [x] refactor startSpan(String spanName, Kind spanKind) in the BaseTracer.java
add startSpan(spanName) to clientTracer => Kind.CLIENT.
- [x] delete httpclientdecorator

### PR DESCRIPTION
**Pull request by heyams**
Solves part of #912

### CODE REVIEW

**Comment by heyams** [comment]
this is a continuation of #967

**Comment by heyams** [comment]
why is this closed?  i didn't close it... what's wrong with github?

**Comment by heyams** [comment]
force-push closed the pr? can someone help?

**Comment by trask** [comment]
It looks like you force pushed `master` to this PR (interesting that caused github to close the PR).

You can use `git reflog` locally to recover the changes in your branch (or I also have a recent copy of your branch locally that I can push back)

**Pull request closed without merging**
