### PR TITLE
add daemon attribute to process.runtime.jvm.threads.count

### PR DESCRIPTION
**Pull request by tuhao1020**
Signed-off-by: HaoTu <haotu@alauda.io>

#6561  has closed

### CODE REVIEW

**Comment by tuhao1020** [comment]
image
What is the problem? @trask

**Comment by trask** [comment]
ya, this is not related to your PR, we will fix in main and let you know so you can pull in main after its fixed

**Comment by laurit** [comment]
@tuhao1020 jApiCmp issue should be fixed now, please rebase

**Comment by tuhao1020** [comment]
@laurit  done

**Review by mateuszrzeszutek — APPROVED** [review]
LGTM 👍 

@jack-berg @jonatan-ivanov PTAL

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by trask** [comment]
@tuhao1020 would you mind also submitting a PR to update the spec?

**Comment by tuhao1020** [comment]
@trask with pleasure, is this file? https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md

**Comment by mateuszrzeszutek** [comment]
> @trask with pleasure, is this file? https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md

That's correct 👍

**Comment by tuhao1020** [comment]
@trask  @mateuszrzeszutek https://github.com/open-telemetry/opentelemetry-specification/pull/2828

**Comment by trask** [comment]
> @trask @mateuszrzeszutek [open-telemetry/opentelemetry-specification#2828](https://github.com/open-telemetry/opentelemetry-specification/pull/2828)

thx!

**Pull request merged**
