### PR TITLE
Bump up Gradle plugin dependencies

### PR DESCRIPTION
**Pull request by jprinet**

### CODE REVIEW

**Comment by anuraaga** [comment]
Thanks @jprinet - can you sign the CLA?

**Comment by jprinet** [comment]
> Thanks @jprinet - can you sign the CLA?

I'm on my way, I need to find the CLA manager at Gradle for this 😅

**Comment by trask** [comment]
@jprinet any luck? 🍀

**Comment by jprinet** [comment]
> @jprinet any luck? 🍀

still after it 😞

**Comment by jprinet** [comment]
> @jprinet any luck? 🍀

This eventually got sorted out @trask 😅

**Review by trask — APPROVED** [review]
> This eventually got sorted out @trask 😅

thx!

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by laurit** [comment]
@jprinet could you rebase this pr, it should get rid of the build failure

**Comment by jprinet** [comment]
> @jprinet could you rebase this pr, it should get rid of the build failure

The rebase clean all the failures indeed 👍

**Review by laurit — APPROVED** [review]
thanks

**Pull request merged**
