### PR TITLE
Enhancement/add additionalServerExtractors

### PR DESCRIPTION
**Pull request by arik-dig**
fixes issue #7153

### CODE REVIEW

**Comment by arik-dig** [comment]
@trask can you please help?
I don't think its related to this PR, but it seems like Github job **testLatestDeps** is failing with:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':instrumentation:aws-sdk:aws-sdk-1.11:library:test'.
> > Could not resolve all task dependencies for configuration ':instrumentation:aws-sdk:aws-sdk-1.11:library:testRuntimeClasspath'.
>    > Could not resolve com.amazonaws:aws-java-sdk-sqs:latest.release.
>      Required by:
>          project :instrumentation:aws-sdk:aws-sdk-1.11:library
>       > Failed to list versions for com.amazonaws:aws-java-sdk-sqs.
>          > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-sqs/maven-metadata.xml.
>             > Could not HEAD 'https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-sqs/maven-metadata.xml'.
>                > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/146.75.28.215] failed: Connect timed out
> 

               
here's the link: https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/3460309292/jobs/5776722669

**Comment by mateuszrzeszutek** [comment]
> @trask can you please help? I don't think its related to this PR, but it seems like Github job **testLatestDeps** is failing with:

It looks like there were some maven/network hiccups; we've been having lots of these recently. I reran the failing jobs, 🤞 that it passes this time.

**Comment by arik-dig** [comment]
> > @trask can you please help? I don't think its related to this PR, but it seems like Github job **testLatestDeps** is failing with:
> 
> It looks like there were some maven/network hiccups; we've been having lots of these recently. I reran the failing jobs, 🤞 that it passes this time.

I tried to rerun and now it fails on something else
```
* What went wrong:
Could not determine the dependencies of task ':instrumentation:jsp-2.3:javaagent:test'.
> Could not resolve all task dependencies for configuration ':instrumentation:jsp-2.3:javaagent:testRuntimeClasspath'.
   > Could not resolve org.apache.tomcat.embed:tomcat-embed-core:latest.release.
     Required by:
         project :instrumentation:jsp-2.3:javaagent
      > Cannot find a version of 'org.apache.tomcat.embed:tomcat-embed-core' that satisfies the version constraints:
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-core:latest.release'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-jasper:10.1.2' (runtime) --> 'org.apache.tomcat.embed:tomcat-embed-core:10.1.2'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-core:{strictly 9.+}'

   > Could not resolve org.apache.tomcat.embed:tomcat-embed-jasper:latest.release.
     Required by:
         project :instrumentation:jsp-2.3:javaagent
      > Cannot find a version of 'org.apache.tomcat.embed:tomcat-embed-jasper' that satisfies the version constraints:
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-jasper:latest.release'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-jasper:{strictly 9.+}'

   > Could not resolve org.apache.tomcat.embed:tomcat-embed-core:{strictly 9.+}.
     Required by:
         project :instrumentation:jsp-2.3:javaagent
      > Cannot find a version of 'org.apache.tomcat.embed:tomcat-embed-core' that satisfies the version constraints:
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-core:latest.release'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-jasper:10.1.2' (runtime) --> 'org.apache.tomcat.embed:tomcat-embed-core:10.1.2'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-core:{strictly 9.+}'

   > Could not resolve org.apache.tomcat.embed:tomcat-embed-jasper:{strictly 9.+}.
     Required by:
         project :instrumentation:jsp-2.3:javaagent
      > Cannot find a version of 'org.apache.tomcat.embed:tomcat-embed-jasper' that satisfies the version constraints:
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-jasper:latest.release'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-jasper:{strictly 9.+}'

   > Could not resolve org.apache.tomcat.embed:tomcat-embed-core:10.1.2.
     Required by:
         project :instrumentation:jsp-2.3:javaagent > org.apache.tomcat.embed:tomcat-embed-jasper:10.1.2
      > Cannot find a version of 'org.apache.tomcat.embed:tomcat-embed-core' that satisfies the version constraints:
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-core:latest.release'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-jasper:10.1.2' (runtime) --> 'org.apache.tomcat.embed:tomcat-embed-core:10.1.2'
           Dependency path 'io.opentelemetry.dummy.jsp-2.3:javaagent:1.20.0-alpha-SNAPSHOT' --> 'org.apache.tomcat.embed:tomcat-embed-core:{strictly 9.+}'

```           

https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/3462240877/jobs/5780874426

any ideas?

**Review by trask — APPROVED** [review]
thx @arik-dig!

**Comment by trask** [comment]
@arik-dig heads up I merged main into your branch to fix the CI failures

**Comment by arik-dig** [comment]
@trask, @mateuszrzeszutek seems like the build passed successfully, thanks.
https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/3467495467

however I cannot merge back to origin main, can you please do it, or give me the permission to do so?

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by mateuszrzeszutek** [comment]
Merged. Thanks @arik-dig !

**Pull request merged**
