### PR TITLE
Instrumenting additional Akka server methods

### PR DESCRIPTION
**Pull request by zackman0010**
Previous PR #6109. Opened a new PR to use a different branch in my fork so that my fork can have a clean `main`.

Add support for auto-instrumentation of Akka's IncomingConnection.handleWith and HttpExt.bindAndHandle methods. Both methods utilize a custom BidiGraphStage to wrap a request in instrumentation. A PinnedDispatcher is utilized to make sure the graph stage runs on the same thread for both request and response handling, preventing scope leakage.

Fixes https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6081 and https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5137

Co-authored-by: Jeremy Ingle [jingle@cspire.com](mailto:jingle@cspire.com)

### CODE REVIEW

**Comment by zackman0010** [comment]
Just confirming that the CLA is still in process here. I confirmed with my manager that it's still in the pipeline, it's just taking a while. It's the first time we've contributed to open source, so there's no existing protocol for this kind of request to go through.

**Comment by trask** [comment]
hi @zackman0010! any objection to closing this (just trying to clean up the backlog a little), and you can re-open when you are able to sign the CLA? I think if I close it you won't be able to re-open it, but if you close it, I think you will be able to re-open yourself. And of course you can always ping on the closed PR and one of us will re-open it if that fails.

also, I'm curious if DCO would be easier for you/your company compared to SLA, check out recent discussion going on about CLA vs DCO in the OpenTelemetry community repo: https://github.com/open-telemetry/community/issues/1252

**Comment by zackman0010** [comment]
@trask Sure, we can do that. I'm sorry again that we haven't had any progress for so long. Our manager has been caught up in another project for several months, and without someone actively working on getting the CLA signed the whole process is stuck. It's a shame because we were very excited to contribute.

I'll bring it back up again and see if we can get it picked back up, but if that doesn't work I'll go ahead and close the MR.

As for CLA vs DCO, I don't know enough about the legal side of things to comment, but I imagine that it would run into the same issues here. After reading the thread, though, my personal opinion as a developer is that I like the suggested hybrid approach. I don't have a problem with signing the CLA, and I'd rather not risk forgetting to sign off on a commit and having to rebase the branch to fix it.

**Comment by zackman0010** [comment]
As discussed, closing this PR until our CLA is taken care of.

**Pull request closed without merging**
