### PR TITLE
fix spring-webflux cast to PathPattern throws ClassCastException

### PR DESCRIPTION
**Pull request by wang007**
when ServerWebExchange.getAttributes().put(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE, "path string type").
opentelemetry javaagent will throw exception.
[企业微信截图_76344afd-4541-482c-a90f-0606ad720351](https://user-images.githubusercontent.com/15957476/195615160-45559fb5-5e0c-4c25-8678-7d8aa603f346.png)

### CODE REVIEW

**Review by trask — APPROVED** [review]
thx!

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by mateuszrzeszutek** [comment]
Hey @wang007 ,
Can you run `./gradlew :spotlessApply` and commit? That should fix the failing spotless job. Thanks!

**Comment by wang007** [comment]
Hey @mateuszrzeszutek 
done.

**Comment by mateuszrzeszutek** [comment]
Thanks!

**Comment by wang007** [comment]
hey, @trask 
when this commit release ?

**Pull request merged**
