### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**

### CODE REVIEW

**Comment by mateuszrzeszutek** [comment]
Looks like we'll have to wait for a stable logback release first

**Comment by mateuszrzeszutek** [comment]
Looks like "our" slf4j (version 2) is conflicting with slf4j from tested libraries (like spring boot; version 1.x): `java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder`

I wonder if we should just get rid of any slf4j references from our tests, and replace them all with JUL. @trask WDYT?

**Comment by trask** [comment]
> I wonder if we should just get rid of any slf4j references from our tests, and replace them all with JUL. @trask WDYT?

makes sense to me given the breaking slf4j changes

**Comment by laurit** [comment]
> I wonder if we should just get rid of any slf4j references from our tests, and replace them all with JUL. @trask WDYT?

It is probably not going to be that easy. At least armeria and testcontainers uses slf4j so you'll probably have to do some shading.

**Comment by mateuszrzeszutek** [comment]
> It is probably not going to be that easy. At least armeria and testcontainers uses slf4j so you'll probably have to do some shading.

We can shade armeria, and redirect its logs to JUL, that's a minor problem. Testcontainers though... 

The overall goal here should be to decouple the slf4j version used inside the javaagent (and remove it from the `dependencyManagement` perhaps) from the slf4j version(s) used inside the tests; so maybe it would be just fine to leave it unspecified and let gradle determine what version to use via transitive dependencies.

**Review by trask — APPROVED** [review]

**Pull request merged**
