### PR TITLE
AgentInstrumentationSpecificationTest add verifications

### PR DESCRIPTION
**Pull request by breedx-splk**
This test is weird. It looks to be checking that classes in bootstrap packages are loaded by the bootstrap classloader. But there are no assertions around this actually happening, only around failures...which could pass if no classes were even attempted.

So this adds a couple assertions that at least 1 class was attempted and at least 1 class was loaded. If these assertions fail, then I think that this means that this test does not actually provide value. 

It fails locally, but I'm submitting a PR to check to see if it might pass in CI under some other classloader shenanigans.

### CODE REVIEW

**Comment by breedx-splk** [comment]
It looks like it fails under `test2` but not under `test0` or `test1` or whatever.
image

**Comment by laurit** [comment]
> It looks like it fails under `test2` but not under `test0` or `test1` or whatever. Perhaps someone can help clarify what those different runs (targets? configurations? I don't even know the correct vernacular!) are and why this would pass in some and fail in others....and maybe what we should do about this.
> 

These are suites. We split tests 4 ways and run these suites in parallel, this test happens to be part of `test2` suite. I'm not a fan of the way we currently split the tests. It is impossible to tell what is in `test2` based on the name. It would probably be better to split into `testCore`, `testInstrumentationAtoK`, `testInstrumentationLtoS` etc. This could also reduce useless work as all test configurations of a given module would be in the same suite this way.
To me it looks like the class path extraction this test uses works only on jdk8 on newer javas `java.class.path` doesn't contain the agent jar

**Comment by mateuszrzeszutek** [comment]
```
    !bootstrapClassesAttempted.isEmpty()
    ||                         |
    |[]                        true
    false
```
I think this test might simply not work correctly on Java 9+; most likely the computed classpath is empty.

**Comment by laurit** [comment]
> I think this test might simply not work correctly on Java 9+; most likely the computed classpath is empty.

It is not empty but it is missing the agent jar and doesn't have any classes that would match the bootstrap package prefixes.

**Comment by breedx-splk** [comment]
Well, I guess I don't have the time to circle back on this. Rather than letting it fester, I'm going to just close it. 

I still think it's a drag that a suite runs and does all this work without assertions, and I'm still kinda confused about the purpose of this test...but maybe it's a "well it's better than nothing and if it crashes at least we'll get breakage". Maybe someone else can pick this up in the future.

**Pull request closed without merging**
