### PR TITLE
Update Liberty versions

### PR DESCRIPTION
**Pull request by fmhwong**
Open Liberty version 20.0.0.x are out of support.  This PR removes 20.0.0.x and adds 22.0.0.x.

### CODE REVIEW

**Comment by fmhwong** [comment]
It looks like we are missing the new images for the new Open Liberty versions.  Is this something that an external contributor can do?   Where can I find the instructions on how to build and push the `smoke-test-servlet-liberty` images?

**Comment by laurit** [comment]
@fmhwong These images are built automatically from https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/8a7e8a8ca203a3ffbfd4baeb322213f600bc05de/smoke-tests/images/servlet/build.gradle.kts#L34-L39 If you wish to adda new version your firstly need to send a pr that adds the new image. When it is merged the images will be published. After that you can use the images in you tests, you'll also have to update https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/8a7e8a8ca203a3ffbfd4baeb322213f600bc05de/smoke-tests/src/test/groovy/io/opentelemetry/smoketest/AppServerTest.groovy#L57 with the value that matches the newly built images.

**Comment by fmhwong** [comment]
Created PR #7878 for creating new Open Liberty images.

**Comment by trask** [comment]
you can see the new tag "20230222.4247218894" now:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pkgs/container/opentelemetry-java-instrumentation%2Fsmoke-test-servlet-liberty

**Comment by laurit** [comment]
@fmhwong the problem is that was8.5.5.19 image build wasn't completely successful. Examine the output of https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/4247069738/jobs/7384671536 We add configuration scripts to change the default port and install our default application. These didn't run successfully as wasmin seem to have failed to connect to the server.

**Comment by laurit** [comment]
@fmhwong we have update websphere images. Use tag `20230301.4309128636` and update websphere versions to `8.5.5.22` and `9.0.5.14`.

**Comment by fmhwong** [comment]
@laurit All checks passed.  Thank you for your help!

**Review by trask — APPROVED** [review]

**Review by laurit — APPROVED** [review]

**Pull request merged**
