### PR TITLE
Fix class cast exception, noop meter does not implement incubating api

### PR DESCRIPTION
**Pull request by laurit**
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11928

### CODE REVIEW

**Comment by zeitlinger** [comment]
I think ExtendedSpanBuilder suffers from the same problem

**Review by trask — APPROVED** [review]

**Comment by trask** [comment]
do we need this if https://github.com/open-telemetry/opentelemetry-java/pull/6617 lands?

**Comment by zeitlinger** [comment]
> do we need this if [open-telemetry/opentelemetry-java#6617](https://github.com/open-telemetry/opentelemetry-java/pull/6617) lands?

one is about tracer, the other for metrics

**Comment by zeitlinger** [comment]
> > do we need this if [open-telemetry/opentelemetry-java#6617](https://github.com/open-telemetry/opentelemetry-java/pull/6617) lands?
> 
> one is about tracer, the other for metrics

the sdk implementation supports everything - I have to check how they would work together

**Comment by zeitlinger** [comment]
> > > do we need this if [open-telemetry/opentelemetry-java#6617](https://github.com/open-telemetry/opentelemetry-java/pull/6617) lands?
> > 
> > 
> > one is about tracer, the other for metrics
> 
> the sdk implementation supports everything - I have to check how they would work together

the sdk implementation doesn't help us, because we implement the interfaces manually: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/436184002c26f5d01594460afb122bab8603d7f7/instrumentation/opentelemetry-api/opentelemetry-api-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/opentelemetryapi/trace/ApplicationTracerProvider.java#L15

**Pull request merged**
