### PR TITLE
Run muzzle during PR

### PR DESCRIPTION
**Pull request by iNikem**
Every module as a separate job

### CODE REVIEW

**Comment by anuraaga** [comment]
I don't think our config for muzzle has enabled caching but I see `FROM-CACHE` in the logs. Do you know how this is happening?

**Comment by anuraaga** [comment]
Do you mind doing a run with cache disabled to measure the time? Some changes, like updating Gradle, will invalidate all cache. That doesn't mean we have to stick with CircleCi but knowing how the worst case does will be helpful. For example, if worst case of CircleCi is 30min and GHA is 4 hours, I don't know what to do.

**Comment by iNikem** [comment]
Buildscan claims that we saved 15s due to remote cache. It just needs to compile couple of modules. Probably tests will still be the longest checks

**Comment by iNikem** [comment]
@anuraaga Tried. Tests are still the longest part.

**Comment by anuraaga** [comment]
@iNikem Something magical is going on or I'm not being able to read the logs correctly - isn't https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1324/commits/ab6b2cab66dffb4357fe9570a89a1c8adccb6410 also printing a lot of FROM-CACHE?

**Comment by iNikem** [comment]
Screenshot 2020-10-05 at 18 47 51

Don't see

**Comment by anuraaga** [comment]
Perhaps it depends on the version. I think your icon on this screenshot makes it clear right? :-)

image

**Comment by anuraaga** [comment]
Ah - nevermind, why am I not looking at muzzle. Got it

**Comment by anuraaga** [comment]
Here's a muzzle with cache (fairly confident this time but still may be doing something silly :P). Any idea why it could be? That being said, of course if unmuzzled cache is still fast it's ok, but TBH I'm just a bit surprised since muzzle seems so intence.

image

**Review by anuraaga — APPROVED** [review]
Why is muzzle so fast even though it seems like it should be really expensive?

**Review by trask — COMMENTED** [review]
Nice 😄
 
image

**Review by trask — APPROVED** [review]

**Pull request merged**
