### PR TITLE
Disable smoke tests in release build since we can't run them inline w…

### PR DESCRIPTION
**Pull request by anuraaga**
…ith other builds effectively.

### CODE REVIEW

**Comment by anuraaga** [comment]
This is good motivation to revisit using a github action to query the status of the `main-build` and just not run any tests in `release-build`. I had issues with a simple approach when I first tried it several months ago but I'm sure it must be possible

**Comment by iNikem** [comment]
If we split release job into several steps, we then can run all the tests. But this requires making sure that all steps actually use the same commit.

I am still uneasy about building and publishing artifacts without testing them. Yes, even if commit is the same, build env may unexpectedly change from the time of `main` build.

**Comment by anuraaga** [comment]
> If we split release job into several steps, we then can run all the tests. But this requires making sure that all steps actually use the same commit.

@iNikem Do you think we should block the next release on this or can temporarily disable?

**Comment by iNikem** [comment]
We can disable for now

**Comment by anuraaga** [comment]
@iNikem Cool - I filed #2993 so I guess we can merge this one?

**Review by iNikem — APPROVED** [review]

**Pull request merged**
