### PR TITLE
Upgrade to latest SDK snapshot

### PR DESCRIPTION
**Pull request by anuraaga**
Confirmed smoke tests built locally pass, they won't pass on CI for this PR.

### CODE REVIEW

**Comment by iNikem** [comment]
If smoke tests will not pass for this PR we cannot merge this PR. Is it possible to make a separate change to prepare smoke tests apps for this?

**Comment by anuraaga** [comment]
Do you mean versioning the smoke test images? If so I could do that yeah.

**Comment by iNikem** [comment]
Versioning is already being done in #1552

I meant that if code changes require new smoke test images, then it makes sense first to make a PR for those images and then a PR which introduce code changes.

**Comment by anuraaga** [comment]
But it's so far a chicken egg issue - rebuilt smoke test images would fail until the new code is in. So with the versioning it will be ok.

**Review by trask — APPROVED** [review]

**Comment by anuraaga** [comment]
Noticed that the recent updates to smoke tests building updated them to a version that passes this build (and fails the rest). So going to go ahead and merge if this goes green but accept-pr might have flaked.

**Pull request merged**
