### PR TITLE
Update groovy import order to match default IntelliJ (#1708)

### PR DESCRIPTION
**Pull request by mcmho**
* organized imports for .groovy files to follow default IntelliJ import settings

* updated intellij-setup.md

* reformat lines with missing empty space

### CODE REVIEW

**Comment by trask** [comment]
hey @mcmho! it looks like there may be a couple of missing imports which is causing the CI failure

**Comment by mcmho** [comment]
> hey @mcmho! it looks like there may be a couple of missing imports which is causing the CI failure

@trask ,  got it!   I'm on it!

**Comment by trask** [comment]
@mcmho it looks like the screenshot needs to be updated, and then i think we'll be good to merge

**Comment by trask** [comment]
> Thanks @trask! sorry had issue with my dev env. but will get better.

no worries, thanks for diving in!

**Review by trask — APPROVED** [review]
thx!

**Pull request merged**
