### PR TITLE
Migrate test docker images to GHCR.

### PR DESCRIPTION
**Pull request by anuraaga**
With the hopes that it is less flaky than bintray's docker repo. Pushed the images manually from my computer to bootstrap.

Also only references versioned images to allow updating smoke-tests without disrupting other PRs.

### CODE REVIEW

**Review by trask — APPROVED** [review]
is there an advantage to embedding the version in the image name instead of using tag?

**Comment by trask** [comment]
> is there an advantage to embedding the version in the image name instead of using tag?

nevermind me, just realized there's a single image name and everything got moved over into the tag 👍

**Comment by iNikem** [comment]
> > is there an advantage to embedding the version in the image name instead of using tag?
> 
> nevermind me, just realized there's a single image name and everything got moved over into the tag 👍

Why this change? I think the old naming scheme is better.

**Comment by anuraaga** [comment]
@iNikem It's mainly to be able to add new images without having to ask an org admin every time. Separate images is a bit better, but don't know if enough to deal with that, or failed bintray pushes.

**Comment by iNikem** [comment]
Don't see how this can eliminate bintray pushes :)

But if we have to ask org admin every time we want to create a new image, that may be a reason enough. Unfortunate, but sufficient.

**Review by iNikem — APPROVED** [review]

**Comment by anuraaga** [comment]
@iNikem I meant bintray pushes of the docker images, they fail a lot right?

**Comment by iNikem** [comment]
Yeah, but do you think that "tag pushes" will be more stable than "name pushes"?

**Comment by anuraaga** [comment]
No clue unless we try :) So far so good

**Pull request merged**
