### PR TITLE
Initialize Config for library instrumentations

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
Extracted from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2434

It turns out that this `Config` fix is needed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2263

### CODE REVIEW

**Review by trask — APPROVED** [review]
approving in case this is needed as temporary measure, otherwise it sounds like there's agreement with @anuraaga proposal that library instrumentation will only support programmatic configuration

**Comment by anuraaga** [comment]
Yeah - either way moving back to programmatic will be easier once there's a flag in the first place :)

**Review by anuraaga — APPROVED** [review]

**Comment by anuraaga** [comment]
Should we merge this or just #2434?

**Comment by trask** [comment]
> Should we merge this or just #2434?

Sounds good, I marked it ready

**Review by iNikem — APPROVED** [review]

**Pull request merged**
