### PR TITLE
Update gradle to 7.5.1

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**

### CODE REVIEW

**Review by laurit — APPROVED** [review]

**Review by trask — APPROVED** [review]

**Comment by trask** [comment]
fyi I bumped this to 7.5.1 just to see if that helped, but same error still

**Comment by laurit** [comment]
https://github.com/mateuszrzeszutek/opentelemetry-java-instrumentation/pull/47 adds the `--add-opens` needed to get the tests passing. Alternatively I guess we could add these to `org.gradle.jvmargs`.

**Comment by mateuszrzeszutek** [comment]
@laurit WDYT about adding these JVM args to the `otel.java-conventions` gradle script instead? Could save us a lot of copy-paste

**Comment by laurit** [comment]
@mateuszrzeszutek that is definitely an option. A potential benefit of not doing it would be that this could mask bugs in agent that cause it to fail without these arguments, but that doesn't seem like a big issue as we also have smoke tests that would take care of catching such issues.

**Comment by trask** [comment]
@laurit any idea why this only started to be a problem in gradle 7.5?

**Comment by laurit** [comment]
> @laurit any idea why this only started to be a problem in gradle 7.5?

@trask gradle used to add
```
--add-opens
java.base/java.util=ALL-UNNAMED
--add-opens
java.base/java.lang=ALL-UNNAMED
```
by default, see https://github.com/gradle/gradle/issues/19771

**Review by trask — APPROVED** [review]
I like keeping the `--add-opens` scoped to the instrumented library that needs them 👍

**Comment by mateuszrzeszutek** [comment]
> I like keeping the `--add-opens` scoped to the instrumented library that needs them 👍

Gotcha. I'm merging this PR then, since I'm fine with both solutions.
Thanks for help with this @laurit !

**Pull request merged**
