### PR TITLE
Remove commons-codec (not needed?)

### PR DESCRIPTION
**Pull request by breedx-splk**
I couldn't find any real usages, so I figured I would see what breaks.

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
A lot of these are for managing transitive dependencies, mostly for the hope of reducing indexing time during development (as futile as that may be...). Instead of removing, how about adding a comment clarifying that these are also for transitives?

**Comment by breedx-splk** [comment]
> A lot of these are for managing transitive dependencies, mostly for the hope of reducing indexing time during development (as futile as that may be...). Instead of removing, how about adding a comment clarifying that these are also for transitives?

Ok, yeah that makes sense. I'll put add it back and add a note about the purpose/intent. But yeah, indexing time...ugh! 🤪

**Comment by breedx-splk** [comment]
Well this turned out to be kinda silly because there was already a perfectly good comment above that also applied to the set below, so I tried to summarize and reference the more detailed explanation. Sorry and thanks.

**Review by trask — APPROVED** [review]
👍

**Review by anuraaga — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]

**Pull request merged**
