### PR TITLE
Update Armeria for testing

### PR DESCRIPTION
**Pull request by anuraaga**

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Review by iNikem — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by iNikem** [comment]
That shows some trust :D Almost all testing jobs are red, but we already have 3 approvals! :D

**Comment by laurit** [comment]
@anuraaga could you rebase. The vert.x issue that made tests fail should be solved.

**Comment by anuraaga** [comment]
@laurit Yeah I had updated today I think in the latest merge commit. Didn't dig into what could still be an issue yet, including the possibility of a bad merge.

**Comment by laurit** [comment]
@anuraaga I think I know what it is, vertx-reactive-3.5 is also using absolute url when relative it expected. I'll try to fix it.

**Comment by anuraaga** [comment]
@laurit Thanks a lot for so much help on this

**Pull request merged**
