### PR TITLE
Allow specifying a JAR to control OTel SDK SPI.

### LINKED ISSUE #427: Loadable initializer
Currently, it is possible to load an exporter in the agent by passing a jar

https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/agent-tooling/src/main/java/io/opentelemetry/auto/tooling/TracerInstaller.java#L56

It would be nice if this could be made more general by executing a generic initializer so a vendor could configure the agent to optimize the experience. For example, for xray we'd like to customize `IdsGenerator` and `Propagation` along with `SpanExporter`. Currently I don't think the former are customizable at all, and having separate customization points for each works ok too, ideally we could have a single entrypoint so users don't have to set as many system properties.

### PR DESCRIPTION
**Pull request by anuraaga**
Didn't hear back on #427 so just sending this as a prototype. Open to any feedback, including closing this PR if it's too far away from where things should be. 

The OTel SDK uses SPI to allow configuring global configuration such as

- Trace ID generation
- Resource

Currently, because the agent runs in its own class loader, it is not possible for a user to customize these knobs at all. I added a property to specify a jar that contains a `TraceProvider` so the SDK picks it up with SPI. The provider I am using is here

https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/blob/both-otel-and-xray/awsagentprovider/src/main/java/com/softwareaws/xray/opentelemetry/exporters/AwsTraceProvider.java

It's definitely not trivial to create one of these jars as it needs to use the shaded API

https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/tree/both-otel-and-xray/awsagentprovider/src/main/resources/META-INF/services

so if this is the approach to go with, it has to be with the caveat that it is a very advanced use case.

I can't think of other approaches though besides adding to the Java SDK something like `OpenTelemetrySdk`.overrideTracerProvider so the default tracer provider can override. Even this may not work without shading through since even though the SDK is not shaded, the API is.

Let me know if you have any thoughts! If this approach doesn't seem terrible I'll add tests and clean it up. I realize I probably should be using `Config` but I believe that will require some hoops to ensure `Config` is loaded in this agent classloader, which is what I'm trying to initialize in the first place.

Without this option, I append to the bootstrap classpath.

https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/blob/both-otel-and-xray/frontend/Dockerfile#L45

This half-works - unfortunately I have to package the SDK with my jar since it needs to be in the bootstrap classpath, while the agent only includes it in the agent classpath. This causes apps to behave fine for the most part but can't use methods like `OpenTelemetry.getTracerProvider().currentSpan()` which produces a classcastexception and if the dependencies don't align well with the app it'll crash. So hopefully to get to a proper solution :)

Fixes #427

### CODE REVIEW

**Comment by trask** [comment]
Hey @anuraaga, thanks for sending the PR, it really helped bring clarity for me.

In cases like this, vendors in this project are generally thinking to build their own agent jar file that contains both opentelemetry-auto and their own stuff (we still have work to do to make this possible without them having to fork the project, see [this related gitter discussion](https://gitter.im/open-telemetry/opentelemetry-auto-instr-java?at=5ec324d5b0256038f9da680b)).

This way vendors' users can consume everything as a single agent jar file (including the exporter).

I'm curious if this approach would work well for you also?

[btw, ignore the test failure on this PR, it's because `test_latest` runs against latest dependency versions found in maven central, and it looks like there's a new version of Finatra just released today that is breaking our tests]

**Comment by anuraaga** [comment]
Thanks for the Gitter link - looks like people are looking for pluggability.

To be honest, we haven't settled on how to deliver to the user yet. A single custom agent jar is definitely an option to reduce knobs for a user. But I hope even such a jar is effectively just setting OTel flags programmatically. We definitely want to track upstream closely so a total fork is the last thing I want to do, better would be if we can shade in something from Maven and have a very thin "wrapper agent" invoking upstream code.

I noticed that `Agent` has very little code outside premain but wondering if even that could be moved to the libraries? If `agent-bootstrap` provided the current premain entry point and optionally accepted a URL to a jar (or ClassLoader?), then we'd be able to use that from a wrapping agent.

Downside of a wrapper though is it needs to be released every time this one is, even though while instrumentation will continue to grow, I suspect the initializer would be relatively constant. So even with a programatic hook, having a property to give vendors an option between wrapping agent or extra system property would be nice.

Let me know if this makes sense and any preference on ways of moving on it :)

**Comment by anuraaga** [comment]
@trask Friendly ping - let me know if you have any thoughts on a way to make some progress on the customization story. I'm happy to do the implementation and redo it of we change minds in the process :) Our OTel integration here and in the collector are moving smoothly and this is probably the biggest open question for me right now.

**Comment by anuraaga** [comment]
Hi @trask - as we discussed this morning I've gone ahead and marked this ready for review so we can use it as a starting point for customizations and any future improvements to come :)

**Comment by anuraaga** [comment]
Sure added to the README

**Comment by trask** [comment]
hey @iNikem are you ok with this? (your requested change is blocking merge)

**Comment by iNikem** [comment]
Approved, sorry for the delay.

**Comment by trask** [comment]
no worries, thx!

**Pull request merged**
