### PR TITLE
Update to latest snapshot.

### PR DESCRIPTION
**Pull request by anuraaga**
This is as far as I was able to get today. I added more version pinning than technically needed while troubleshooting baggage not class loadable issue, but I guess it's nice to have as much pinned properly as possible anyways.

Tests fail with more traces being reported than expected (e.g, both server and client span for client test). Not sure why this change would affect that - if anyone has time to run with this branch that's cool, otherwise I'll take another look later.

### CODE REVIEW

**Comment by trask** [comment]
hey @anuraaga! I just opened https://github.com/open-telemetry/opentelemetry-java/issues/1742 for the reason why these tests are failing.

For now at least, looks like we need to configure w3c propagator in AgentTestRunner and TracerInstaller.

On another topic in this PR, my reading of https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#statuscanonicalcode is that we should be setting `ERROR` wherever we were previously setting `UNKNOWN` (or other error conditions), and we should only remove `setStatus` where we were previously setting it to `OK`.

**Comment by anuraaga** [comment]
@trask Not sure, it says "The status code should only be set to ERROR according to the rules defined within the semantic conventions." The only convention I could find was HTTP. @iNikem Do you know how to record the new codes?

**Comment by trask** [comment]
Agree I maybe read the spec with some bias 😂.

What I hope, is that we should set span status to ERROR if we think backends should display that span as an error (I think most backends have this concept, e.g. display the span in red).

Ya, @iNikem will know.

**Comment by trask** [comment]
> if anyone has time to run with this branch that's cool

I have time, will see about finishing this up since master is failing due to jfrog snaphot pruning.

Not sure what to do about setting/not setting ERROR. I think setting ERROR will be closest to what we have currently, and will be easy to remove later as we get clarification (as opposed to removing it now and needing to add it back later), so will probably go that route for now.

**Review by anuraaga — COMMENTED** [review]
Thanks for the help! LGTM.

I presume we'll revisit the status stuff anyways when Nikita creates a table for that one too :D

**Review by trask — APPROVED** [review]

**Comment by iNikem** [comment]
@trask @anuraaga @jkwatson Can we talk about this error status point during our common meeting?

**Comment by trask** [comment]
> @trask @anuraaga @jkwatson Can we talk about this error status point during our common meeting?

Added to [agenda](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw) 👍

**Pull request merged**
