### PR TITLE
Release build can rely on master build checks instead of testing again.

### PR DESCRIPTION
**Pull request by anuraaga**
Had this random idea.

### CODE REVIEW

**Comment by trask** [comment]
should the tests run already if the corresponding commit has been published to the s3 build cache?

**Comment by anuraaga** [comment]
I noticed release build always seems to rerun once - I think it's because the version bump invalidates the cache, presumably by changing manifests. Not sure if there's a way around it in the Gradle config.

**Comment by iNikem** [comment]
I think this is a slippery path. We have not way to be sure that the same git commit, that we use to build published artifacts, was actually tested. If we don't want to re-test before publish/release, then we should just promote already published snapshots. As I proposed in Artifactory-way of releasing.

**Comment by anuraaga** [comment]
This PR checks that the commit trying to be released has passing checks, that solves that issue right?

**Review by iNikem — APPROVED** [review]

**Pull request merged**
