### PR TITLE
Rename grizzly-client instrumentation

### LINKED ISSUE #1658: Rename grizzly-client instrumentation to async-http-client
It appears to just be instrumentation (and tests) of [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client)

Also, I don't think we need to disable it by default (grizzly-server is a different story, and should be disabled by default).

### PR DESCRIPTION
**Pull request by trask**
Closes #1658

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by iNikem** [comment]
I think there is some confusion here.

https://github.com/AsyncHttpClient/async-http-client uses artifactId `async-http-client` and package name `org.asynchttpclient`
https://github.com/eclipse-ee4j/grizzly-ahc uses artifactId `grizzly-http-client` and package name `com.ning.http.client`.

The instrumentation under review monitors the second one, not the first one.

**Review by iNikem — CHANGES_REQUESTED** [review]
See my comment above

**Comment by trask** [comment]
oh ya, `com.ning.http.client` was the package name prior to version `2.0`, I've updated the README to note that we only support `1.9+ (not including 2.x yet)`

**Comment by iNikem** [comment]
Ok, I now understand better what is happening. But I am still not convinced this change is a good one. This instrumentation still was written for https://github.com/eclipse-ee4j/grizzly-ahc, judging from package and artifact names. Why do we want to instead say that this is about old version of https://github.com/AsyncHttpClient/async-http-client? Then we should change gradle build file and test with those artifacts, whose `artifactId=async-http-client-project`

**Comment by trask** [comment]
> Then we should change gradle build file and test with those artifacts

👍 done

**Review by iNikem — APPROVED** [review]

**Pull request merged**
