### PR TITLE
Split out RpcAttributesGetter

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
Part of #5291

I thought it would be useful to split the extractors into `RpcClientAttributesExtractor` and `RpcServerAttributesExtractor` because they will have different `SpanKey`s associated to them; there's only one getter interface though, cause both extractors use it to retrieve the same set of attributes.

### CODE REVIEW

**Review by trask — APPROVED** [review]
> I thought it would be useful to split the extractors into `RpcClientAttributesExtractor` and `RpcServerAttributesExtractor` because they will have different `SpanKey`s associated to them; there's only one getter interface though, cause both extractors use it to retrieve the same set of attributes.

Do you think it makes sense to proactively split the getter as well (similar to http client/server getter) in case rpc client/server attributes diverge in the future?

**Comment by mateuszrzeszutek** [comment]
> Do you think it makes sense to proactively split the getter as well (similar to http client/server getter) in case rpc client/server attributes diverge in the future?

I thought about it too and in the end I couldn't decide whether to do it or not -- I'll try it out and push the change here, let's see if it looks manageable.

**Comment by anuraaga** [comment]
I think unlike HTTP RPC has a stronger tendency to have the same data in server / client so we could probably avoid splitting now.

**Comment by trask** [comment]
> I think unlike HTTP RPC has a stronger tendency to have the same data in server / client so we could probably avoid splitting now.

sounds good, IIRC our current thinking is to not stabilize a semantic attributes extractor until that semantic convention is declared stable, so that gives us some time to see if anything new emerges for rpc

**Comment by trask** [comment]
@mateuszrzeszutek heads up conflicts

**Pull request merged**
