### PR TITLE
Make muzzle generate helperClassNames() method

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
First part of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1374

This PR contains the actual logic behind collecting & ordering helper class names, `helperClassNames()` methods are left untouched to avoid merge conflicts - I'll remove all those methods in a separate PR.

### CODE REVIEW

**Review by trask — COMMENTED** [review]
❤️!!

This just bit me (yet again) 😭, I renamed a helper class and forgot to update the `helperClassNames()`: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1643/commits/2356d5b441cd08fffc006ba96680fe84644d3c4c

I sent a [PR to your branch](https://github.com/mateuszrzeszutek/opentelemetry-java-instrumentation/pull/5) with a couple of potential simplifications. Feel free to add feedback on my PR and we can discuss over there or over here.

**Comment by mateuszrzeszutek** [comment]
> I sent a [PR to your branch](https://github.com/mateuszrzeszutek/opentelemetry-java-instrumentation/pull/5) with a couple of potential simplifications. Feel free to add feedback on my PR and we can discuss over there or over here.

Nice! I love how it simplified the dependency cycle stuff.

**Review by trask — APPROVED** [review]
I sent a small commit directly to your branch to clarify my understanding of what the tests are testing, let me know if looks good

**Comment by mateuszrzeszutek** [comment]
> I sent a small commit directly to your branch to clarify my understanding of what the tests are testing, let me know if looks good

👍  Thanks!

I've added one more assertion for the enum class:

```java
    assertThatContainsInOrder helperClasses, [
      OtherTestHelperClasses.TestEnum.name,
      OtherTestHelperClasses.TestEnum.name + '$1',
    ]
```

**Comment by trask** [comment]
> I've added one more assertion for the enum class

oh yes! I didn't notice that extends relationship 👍

**Comment by trask** [comment]
🎉🎉🎉

**Pull request merged**
