### PR TITLE
Update Protobuf versions for M1 support

### PR DESCRIPTION
**Pull request by zackman0010**
See issue #6242. Creating a PR to show what versions I had to edit to successfully compile on an M1 Mac.

### CODE REVIEW

**Comment by zackman0010** [comment]
@trask Looks like the CI didn't like it, so it unfortunately is a breaking change.

**Comment by anuraaga** [comment]
This unfortunately removes testing against older versions of gRPC which we do need to be able to do, but it's likely the newer version of protoc can't be used with such an old version of gRPC. We may want to just check in the generated sources and remove protoc compilation from the build.

**Comment by trask** [comment]
> We may want to just check in the generated sources and remove protoc compilation from the build.

that's a good idea 👍

**Comment by zackman0010** [comment]
I'll go ahead and close this PR as well.

**Pull request closed without merging**
