### PR TITLE
Add @iNikem as a maintainer

### PR DESCRIPTION
**Pull request by trask**
Nikita has been a significant driver of this project through his code contributions, PR and issue reviews, release process improvements, documentation contributions, and participation in gitter and SIG meeting discussions.

### CODE REVIEW

**Comment by iNikem** [comment]
@tylerbenson @jkwatson I remember you asked to mention you if your attention s needed :)

**Comment by jkwatson** [comment]
If I say 'no', can he come over and work on the Java project itself?  ;)

Yes, approved, although this PR needs to be rebased, and the build is failing.  :)

**Comment by trask** [comment]
:partying_face:

**Comment by iNikem** [comment]
But of course, @jkwatson ! As soon as this project is done, I can help you over there :)

**Pull request merged**
