### PR TITLE
add ktor 3 instrumentation

### PR DESCRIPTION
**Pull request by acunap**
Hi! IntelliJ recently announced that they are going to release their official Ktor instrumentation library but there isn't any release date. So since the changes between Ktor 2 and Ktor 3 are minimal, I'd like to contribute with this library so we can instrument our apps right now.

### CODE REVIEW

**Review by steverao — COMMENTED** [review]
I saw the codes, except one or two line are different from with module of ktor-2.0, others are same. Didn't Ktor-2.0 support version 3.0 after you tested it? If yes, is there any solution to support 3.0 by adjusting the codes in module of Ktor-2.0? BTW, Ktor-2.0 means its supporting at minimal supported version 2.0 instead of only supporting 2.0.

**Comment by acunap** [comment]
> I saw the codes, except one or two line are different from with module of ktor-2.0, others are same. Didn't Ktor-2.0 support version 3.0 after you tested it? If yes, is there any solution to support 3.0 by adjusting the codes in module of Ktor-2.0? BTW, Ktor-2.0 means its supporting at minimal supported version 2.0 instead of only supporting 2.0.

I don't think Ktor-2.0 could support version 3.0 since 3.0 introduce breaking change on its API and objects exposed publicly by server internals.

**Comment by trask** [comment]
> Hi! IntelliJ recently announced that they are going to release their official Ktor instrumentation library but there isn't any release date.

Nice! Do you happen to have a link handy to this announcement? Thanks

**Comment by acunap** [comment]
> > Hi! IntelliJ recently announced that they are going to release their official Ktor instrumentation library but there isn't any release date.
> 
> Nice! Do you happen to have a link handy to this announcement? Thanks

Sure thing, but it's no more than a few lines in their 2024 roadmap.

https://blog.jetbrains.com/kotlin/2024/03/the-ktor-roadmap-for-2024/#opentelemetry-plugins

**Pull request closed without merging**
