### PR TITLE
Polished contributing document

### PR DESCRIPTION
**Pull request by steverao**
Polished contributing document

### CODE REVIEW

**Review by laurit — COMMENTED** [review]
To me this is one sentence that has 2 embedded code snippets. In my opinion capitalizing it this way is not needed.

**Comment by steverao** [comment]
> To me this is one sentence that has 2 embedded code snippets. In my opinion capitalizing it this way is not needed.



> To me this is one sentence that has 2 embedded code snippets. In my opinion capitalizing it this way is not needed.

I think it's a little special here, If they are all in one sentence, without marks will make the sentence look a bit strange. I think the current way they are arranged, it is necessary to first letter capitalized, which looks more coordinate a bit. Sure, I can turn it off if you still don't think it's necessary？

**Comment by trask** [comment]
@theletterf can you give us your expert opinion? Thanks!

**Comment by theletterf** [comment]
So, when you're interspersing code snippets with sentences, it doesn't need a capital letter because it's all part of the same sentence. I think the snippets could use some restructuring though — here's my suggestion, which eliminates the issue and restores a semblance of capitalization. ;)

````
### Avoid using @Advice.Origin

You shouldn't use ByteBuddy's @Advice.Origin method, as it
inserts a call to `Class.getMethod(...)` in a transformed method.

Instead, get the declaring class and method name, as loading
constants from a constant pool is a much simpler operation.

For example:

```java
@Advice.Origin("#t") Class<?> declaringClass,
@Advice.Origin("#m") String methodName
```
````

**Comment by steverao** [comment]
> So, when you're interspersing code snippets with sentences, it doesn't need a capital letter because it's all part of the same sentence. I think the snippets could use some restructuring though — here's my suggestion, which eliminates the issue and restores a semblance of capitalization. ;)
> 
> ```
> ### Avoid using @Advice.Origin
> 
> You shouldn't use ByteBuddy's @Advice.Origin method, as it
> inserts a call to `Class.getMethod(...)` in a transformed method.
> 
> Instead, get the declaring class and method name, as loading
> constants from a constant pool is a much simpler operation.
> 
> For example:
> 
> ```java
> @Advice.Origin("#t") Class<?> declaringClass,
> @Advice.Origin("#m") String methodName
> ```
> ```

Thanks @theletterf! Except using `@Advice.Origin Method method` instead of `@Advice.Origin method` above. I think everything else is great! What do you think? @laurit @trask

**Comment by laurit** [comment]
@theletterf 's suggestion looks good.

**Review by trask — APPROVED** [review]

**Pull request merged**
