### PR TITLE
Upgrade Semconv  to 1.26

### PR DESCRIPTION
**Pull request by crossoverJie**
[v1.26.0](https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.26.0) has been released.

Replace the deprecated attributes with new ones.

### CODE REVIEW

**Comment by crossoverJie** [comment]
@trask @laurit Please take a look.

**Review by SylvainJuge — APPROVED** [review]
LGTM, just a few minor (non blocking) typos.

**Comment by laurit** [comment]
Unfortunately, they way I see it, this PR can not be merged as it is. Have a look at https://opentelemetry.io/docs/specs/semconv/database/ Pay attention to

> Warning Existing database instrumentations that are using [v1.24.0 of this document](https://github.com/open-telemetry/semantic-conventions/blob/v1.24.0/docs/database/_index.md) (or prior) SHOULD NOT change the version of the database conventions that they emit until a transition plan to the (future) stable semantic conventions has been published. Conventions include, but are not limited to, attributes, metric and span names, and unit of measure.

Messaging semantic conventions https://opentelemetry.io/docs/specs/semconv/messaging/messaging-spans/ have a similar warning.
I believe that at least for the database semantic conventions the plan is to use a similar opt-in mechanism that we used for stabilizing the http semantic conventions. @trask is this correct? So just changing the code to use new semantic conventions won't work. You'll need to use the `otel.semconv-stability.opt-in` flag so users can choose whether they want their telemetry with old, new or both semantic conventions. Tests will also need to be modified so that both old and new semantic conventions are tested. If you wish to work on this first have a look at how this was handled in http semantic conventions.

**Comment by SylvainJuge** [comment]
For `otel.semconv-stability.opt-in` we will have to re-introduce it as it was removed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11257 since it was no longer used after the JVM metrics and HTTP conventions were made stable.

From what I remember we plan to make the stable database conventions the default for next major release of instrumentation (so 3.x). Do we have similar plans for other attributes that are covered by this PR (rpc and messsaging) ?

**Comment by crossoverJie** [comment]
@laurit @SylvainJuge Thank you for your responses.

I noticed that `SemconvStability` has been removed. 

Should we add SemconvStability back and include these values:
- db
- db/dup
- messaging
- messaging/dup

**Comment by heyams** [comment]
> @laurit @SylvainJuge Thank you for your responses.
> 
> I noticed that `SemconvStability` has been removed.
> 
> Should we add SemconvStability back and include these values:
> 
> * db
> * db/dup
> * messaging
> * messaging/dup

Yes, i am adding it back while prototyping stable database semconv (#11575). however, it's for `db, db/dup` only. `message and messaging/dup` can be added later when applicable.

**Comment by crossoverJie** [comment]
> > @laurit @SylvainJuge Thank you for your responses.
> > I noticed that `SemconvStability` has been removed.
> > Should we add SemconvStability back and include these values:
> > 
> > * db
> > * db/dup
> > * messaging
> > * messaging/dup
> 
> Yes, i am adding it back while prototyping stable database semconv (#11575). however, it's for `db, db/dup` only. `message and messaging/dup` can be added later when applicable.

Thank you. I will continue to push this forward when your PR is completed, although by then, we might be able to upgrade to version `1.27` 🤣 .

**Comment by crossoverJie** [comment]
Close by #12292

**Pull request closed without merging**
