### PR TITLE
Remove executor queue offer check

### PR DESCRIPTION
**Pull request by trask**
Since we only wrap lambdas, which can't be cast back to their original type, the executor queue offer check doesn't seem necessary.

Inspired by https://github.com/DataDog/dd-trace-java/pull/1752 and https://github.com/glowroot/glowroot/commit/725e7d0f3fe2c261f1e13fa8d31ccaa3e539e809.

cc: @tylerbenson

### CODE REVIEW

**Comment by iNikem** [comment]
So https://github.com/raphw/byte-buddy/issues/558 is not an issue anymore?

**Review by anuraaga — COMMENTED** [review]
TBH I don't know enough about this to review, though the code looks fine :-)

**Comment by trask** [comment]
> So [raphw/byte-buddy#558](https://github.com/raphw/byte-buddy/issues/558) is not an issue anymore?

Lambda classes aren't generally instrumentable (unfortunately they aren't passed to `ClassFileTransformer`).

ByteBuddy has an interesting `LambdaInstrumentationStrategy` that attempts to work around this issue, but seems that issue you pointed to is why we aren't using it.

Instead, we manually wrap the lambdas, and the wrappers (which are not lambdas themselves) are instrumented.

**Comment by trask** [comment]
Oh yeah, and the offer check I suspect was to verify that the executor doesn't try to re-cast the Runnable/Callable back to a known type.

This is what happened to me in https://github.com/glowroot/glowroot/issues/564.

Initially I wasn't propagating context to lambdas. Then when I found I had to wrap them, I figured I may as well wrap everything. And then I got that issue, and backed off and only wrapped lambdas. Which is what this codebase already does.

**Comment by tylerbenson** [comment]
@devinsba do you want to weigh in here?

**Comment by trask** [comment]
Thanks @tylerbenson @devinsba!

@anuraaga @iNikem I suggest that we go forward with this change, given that there are concerns about the queue offer check anyways https://github.com/DataDog/dd-trace-java/pull/1752#discussion_r469370585.

**Review by anuraaga — APPROVED** [review]
LGTM (? :P)

**Review by iNikem — APPROVED** [review]

**Pull request merged**
