### PR TITLE
Save ILoggingEvent.getArgumentArray() arguments from Logback 

### PR DESCRIPTION
**Pull request by igor-suhorukov**
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11861
This PR will solve #11861 to support structured logging in logback logging method with arguments

In legacy java application methods like **log.info("Message {}, {} and {}, arg1,arg2,arg3)** often happens in code.
It would be convenient to store such log arguments in telemetry for log search functionality without using full-text search.

### CODE REVIEW

**Comment by laurit** [comment]
This PR adds an option to capture the unformatted (placeholders not replaced) log message along with arguments that will substitute the placeholders.
I think this will need to be raised at the SIG meeting to get a consensus on how we want to implement it. Dow we want to capture both formatted and the unformatted message, or are we going to capture only one them based on some flag? How are we going to represent the arguments. This PR encodes the arguments with names like `log.body.original.param.0` which does not align with existing practices where we usually represent stuff like that with arrays. Though arrays can only one type so we'd need to convert all the arguments to strings.

**Comment by igor-suhorukov** [comment]
Thank you for feedback @laurit 
I have couple of questions about internal processes and so on. Are you with your colleagues make decisions on this week and write conclusion and recommendation for this PR in comment here?

`Though arrays can only one type`
I can revert my last commit https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11865/commits/1b1f307a658abad02b5a24186807b9864bcc9b21 and it will solves _convert all the arguments to strings_
Could you please point place in project java code where _existing practices where we usually represent stuff like that with arrays_ for attributes?

**Comment by laurit** [comment]
> Are you with your colleagues make decisions on this week and write conclusion and recommendation for this PR in comment here?

There is a weekly SIG meeting on Thursday where such issues can be discussed. You can find the meeting zoom link and the meeting notes doc in the otel community calendar https://calendar.google.com/calendar/u/0/embed?src=c_2bf73e3b6b530da4babd444e72b76a6ad893a5c3f43cf40467abc7a9a897f977@group.calendar.google.com Everybody can attend and add topics to the meeting notes.

> I can revert my last commit https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/1b1f307a658abad02b5a24186807b9864bcc9b21 and it will solves convert all the arguments to strings

I'd wait until this is discussed at the SIG meeting. Perhaps there is some alternative solution.

> Could you please point place in project java code where existing practices where we usually represent stuff like that with arrays for attributes?

For example logback markers https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/460bd3f92a379d219eb2a63f1a85ce2195377727/instrumentation/logback/logback-appender-1.0/library/src/main/java/io/opentelemetry/instrumentation/logback/appender/v1_0/internal/LoggingEventMapper.java#L54 are represented as a string array.

**Comment by igor-suhorukov** [comment]
image

image

**Comment by trask** [comment]
opened https://github.com/open-telemetry/semantic-conventions/issues/1283 to see if we can get any broader perspective / consensus on the semconv issues

**Comment by igor-suhorukov** [comment]
[Meeting conclusions](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw/edit) related to this PR
image

**Review by laurit — APPROVED** [review]

**Pull request merged**
