### PR TITLE
Changed instrumentation tracer" TRACER.startSpan() to never return `null`

### PR DESCRIPTION
**Pull request by trask**
Changed `TRACER.startSpan()` to never return `null`, I think this is less surprising.

### CODE REVIEW

**Comment by iNikem** [comment]
I don't agree with this PR. It forces clients to know/remember all those different steps they have to do in instrumentations: call this method, check that condition, call this method. The idea of semantic tracers was to reduce this "checklist" as much as possible. That checklist has to be coded once, in the corresponding tracer, and not repeated in every instrumentation.

After #465 is done, do you really want _every_ instrumentation to check that before calling `TRACER.startSpan`? I don't :) But current `getAttachedSpan` method is exactly this check and this PR propose to move it out of the TRACER and into every instrumentation. IMO this defeats the purpose of reusable tracers.

**Comment by trask** [comment]
@iNikem what do you think about this for general-ish structure?

```
  @Advice.OnMethodEnter
  public static boolean onEnter(
      ...
      @Advice.Local("otelSpan") Span span,
      @Advice.Local("otelScope") Scope scope) {

    if (TRACER.shouldCreateSpan(...)) {
      span = TRACER.startSpan(...);
      scope = TRACER.withSpan(span);
    }
  }
```

```
  @Advice.OnMethodExit
  public static void onExit(
      ...
      @Advice.Thrown Throwable throwable,
      @Advice.Local("otelSpan") Span span,
      @Advice.Local("otelScope") Scope scope) {

    if (scope == null) {
      return;
    }

    if (throwable == null) {
      TRACER.end(...);
    } else {
      TRACER.endExceptionally(...);
    }
  }
```

**Comment by trask** [comment]
The need for re-scoping is pretty rare (just 1 instrumentation i think?), so i don't think we need to optimize the structure for that case

**Comment by iNikem** [comment]
I almost like `onExit` method. Not so sure about `onEnter`. If we leave out re-scoping, then scope and span are either both null or both not null. Why do we have to call 2 methods to get them? I member that you oppose `SpanWithScope` or similar approach and want to keep span and scope separate. I really would love to hear the rationale behind this. Why `Scope` has no reference to `Span`?

If we do have to separate span and scope, then we have to have some `if` in `onEnter` method and then your proposal is nice.

**Comment by trask** [comment]
> Why Scope has no reference to Span?

I think the main answer is that Scope is just for holding a Context.

You _can_ get the Span from the Context though:

`TracingContextUtils.getSpan(Context.current())`

though
* this won't be `null` if we decide not to create a new span (e.g. if we are nested), since it that case it will return the parent span
* this will not be as efficient as maintaining direct reference to the span

**Comment by trask** [comment]
> I member that you oppose SpanWithScope or similar approach and want to keep span and scope separate. I really would love to hear the rationale behind this.

I like being super explicit about scope/context management.

Ideally scope should always be opened/closed inside of a single method:

```
try (Scope scope = withSpan(span)) {
   ...
}
```

So I'm in favor of staying as close to this as possible, e.g. doing `withSpan(span)` and `scope.close()` directly from `@OnMethodEnter` and `@OnMethodExit`.

Also, `SpanWithScope` is an extra object / memory, and I'm always in favor of eliminating those if the alternative is not too bad.

**Comment by iNikem** [comment]
I see... so it is "scope of a context", not "scope of a span". That makes sense.

Ok, you convinced me for now :) If I raise this question again, just point me to this PR :)

**Comment by trask** [comment]
> wonder if any thoughts on using `@Nullable` annotation in this repo

i've been using [checker framework](https://checkerframework.org/) in glowroot forever 😄 https://github.com/glowroot/glowroot/commit/57f268f52485c1ec9303b4a34d2e2bc8788a7813

so a big fan in general, though checker framework is pretty complex, and i've spent more time than i'd like to admit getting things to pass that required annotating generic type parameters

NullAway sounds better in this regard "a great bang for your buck" 😂

**Comment by iNikem** [comment]
How do we avoid having "yet another checker" which report is completely ignored? We do have checkstyle and codenarc already

**Comment by trask** [comment]
it would probably take a good effort to make NullAway pass, and then we can enforce it during the build. i don't think checkstyle or codenarc target null handling(?)

**Comment by iNikem** [comment]
I did not mean specific check. But "using checker" vs "running and ignoring checker" :)

**Comment by trask** [comment]
yes, agree, 👎 to adding any more checkers that we ignore 😂

**Comment by anuraaga** [comment]
Yup ignored checkers aren't helpful :) Possible checking in the future is nice I think but in the meantime if there aren't concerns with the annotation itself I'll probably use it in PRs since I find the documentation aspect alone to be extremely useful.

**Pull request merged**
