### PR TITLE
Update Jrog link

### PR DESCRIPTION
**Pull request by hasanfd**
Obsolete link updated. Change jfrog folder "auto" => "instrumentation".

### CODE REVIEW

**Review by iNikem — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]
Thanks!

**Comment by anuraaga** [comment]
@hasanfd Do you mind signing the CLA?

**Comment by hasanfd** [comment]
I did it @anuraaga thanks!

**Comment by hasanfd** [comment]
> I did it @anuraaga thanks!

Sorry, @anuraaga. I thought I did it, but it wasn't. I signed the documents now. Is there anything I need to do to trigger the check mechanism again?

**Comment by hasanfd** [comment]
I have opened a support ticket to the Linux foundation for CLA and they resolved it. All green now. Sorry for the inconvenience.

**Review by iNikem — APPROVED** [review]

**Pull request merged**
