### PR TITLE
support mongo 4.10.x connection pool instrumentation

### LINKED ISSUE #12069: Mongo plugin DefaultConnectionPoolInstrumentation does not support 4.10.x
### Describe the bug

The `DefaultConnectionPoolInstrumentation` only support mongo which version is lower to 4.10.0

### Steps to reproduce

image

### Expected behavior

The `getAsync` can propagate the context correctly

### Actual behavior

The `getAsync` can not propagate the context correctly

### Javaagent or library instrumentation version

latest

### Environment

**JDK**:
**OS**:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 123liuziming**
Resolves #12069

### CODE REVIEW

**Comment by laurit** [comment]
@123liuziming could you add a regression test for this? As all the mongo tests are passing I guess we don't have a test that covers this.

**Comment by 123liuziming** [comment]
> @123liuziming could you add a regression test for this? As all the mongo tests are passing I guess we don't have a test that covers this.

Yes, I am trying to cover the scenario.

**Comment by heyams** [comment]
Please add a test for this if you can.

**Comment by 123liuziming** [comment]
I didn't find a case to verify the validity of the PR. Even if we don't do context propagation to `com.mongodb.internal.connection.DefaultConnectionPool`, it seems that the mongo plugin still works fine.

**Comment by 123liuziming** [comment]
Seems like the `AsyncWorkManagerInstrumentation` helps us to propagate the context correctly and make the `DefaultConnectionPoolInstrumentation` redundant in a way.

**Pull request closed without merging**
