### PR TITLE
AWS Lambda Runtime internal handlers need to be ignored from being instrumented and so traced.

### LINKED ISSUE #7808: Non-top level server span created by lambda instrumentation
**Describe the bug**
When using javaagent with AWS Lambda application, instrumentation produces two server spans.
Both of these are applying:
`io.opentelemetry.javaagent.instrumentation.awslambdacore.v1_0.AwsLambdaRequestHandlerInstrumentation`
`io.opentelemetry.javaagent.instrumentation.awslambdaevents.v2_2.AwsLambdaRequestHandlerInstrumentation`

**Steps to reproduce**
Deploy and invoke an sqs lambda handler with the javaagent.

Here's my example:

```java
public class ExampleSQSHandler implements RequestHandler<SQSEvent, String> {
    private static final String TOPIC_ARN = System.getenv("TOPIC_ARN");

    private final SnsClient client = SnsClient.create();

    @Override
    public String handleRequest(SQSEvent event, Context context) {
        PublishRequest.Builder publishBuilder = PublishRequest.builder().topicArn(TOPIC_ARN);
        List<SQSEvent.SQSMessage> records = event.getRecords();
        for (SQSEvent.SQSMessage record : records) {
            String body = record.getBody();
            client.publish(publishBuilder
                    .message("{\"example-success\":" + body + "}")
                    .build());
        }
        // log execution details
        Util.logEnvironment(event, context);
        return "Success!";
    }
}
```

**What did you expect to see?**
Only one server span.

**What did you see instead?**
Two server spans were created.

**What version are you using?**
1.22.1

**Environment**
Lambda java11 runtime

### PR DESCRIPTION
**Pull request by serkan-ozal**
… Otherwise, there might be double root spans.

Fixes #7808

### CODE REVIEW

**Comment by cleverchuk** [comment]
@serkan-ozal please, it looks like we'll need same check [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/8621e841c311435e848f5eb704c199b8e3ea75d6/instrumentation/aws-lambda/aws-lambda-events-2.2/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/awslambdaevents/v2_2/AwsLambdaRequestHandlerInstrumentation.java#L37-L39).

**Comment by serkan-ozal** [comment]
@cleverchuk I had not added it there because of SQSEvent check here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/4fc3bab5d16bf737aec9e05574268d1f4c1aa58b/instrumentation/aws-lambda/aws-lambda-events-2.2/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/awslambdaevents/v2_2/AwsLambdaInstrumentationModule.java#L25

Since `SQSEvent` class is not visible to AWS Lambda Runtime class loader (system class loader), I have thought that it is not needed. But just to be clear and be safe, I may add that check there too, WDYT?

**Comment by cleverchuk** [comment]
@serkan-ozal Gotcha. It looks sufficient to not add anymore code. Thanks for pointing that out.

**Comment by trask** [comment]
cc @tylerbenson

**Pull request merged**
