### PR TITLE
add rpc metrics conventions implement

### PR DESCRIPTION
**Pull request by yangtaoran**
add rpc metrics conventions implement

### CODE REVIEW

**Comment by trask** [comment]
thanks @yangtaoran! let us know if you are able to sign the CLA above

**Comment by yangtaoran** [comment]
Hi @trask ,I have signed the CLA.

**Comment by trask** [comment]
hey @yangtaoran, it looks like the CLA check is failing on some of the commits because they are tied to a different email address (@qq.com). can you try squashing to a single commit tied to the email that you signed the CLA with (@gmail.com) and force pushing? hopefully that should resolve the CLA check, thx!

**Comment by trask** [comment]
hi @yangtaoran, sorry about the CLA check, it looks like there are still commits in this PR that have author (@qq.com) which has not signed. it may be easier to close this PR and re-stage your changes as a single commit with author (@gmail.com) which has signed, and open a fresh PR. let us know if we can help. thx!

**Comment by yangtaoran** [comment]
hi @trask ,I'm sorry, I plan to close the PR and checkout a new branch to resubmit a new PR

**Pull request closed without merging**
