### PR TITLE
Remove khttp instrumentation

### PR DESCRIPTION
**Pull request by anuraaga**
The project doesn't seem to really be maintained. I think presence in Maven Central is a reasonable bar for a library to be included in our distro.

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]
> Stable releases are hosted on JCenter.

[source](https://github.com/ascclemens/khttp#stable)

Yep, let's remove that one.

**Review by trask — APPROVED** [review]
cc: @iNikem https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/401#issue-416872494

**Comment by anuraaga** [comment]
@trask Thanks for the reference. Won't merge until @iNikem approves too

**Review by iNikem — CHANGES_REQUESTED** [review]
I will ask around if we still need it. Will block this PR for a couple of days until I hear back.

**Comment by anuraaga** [comment]
Thanks @iNikem - also keep in mind the option of adding it back to splunk distro :)

**Comment by iNikem** [comment]
Yes, I remember that :)

**Comment by anuraaga** [comment]
Been a few days - statue of limitations expired? :)

**Review by iNikem — APPROVED** [review]
Yeah, putting my maintainer hat on, I guess it is reasonable to remove it...

**Pull request merged**
