### PR TITLE
Clarify jaeger/zipkin exporter property in README page

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by yue9944882** [comment]
surprisingly there's also something wrong w/ the zipkin documents.. i tried `ota.exporter.jaeger.endpoint` and `ota.exporter.jaeger.service.name` out heuristically :)

**Comment by iNikem** [comment]
Are you sure about this change? This was changed recently in #674 to match properties used by otel-java: https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java

**Comment by trask** [comment]
Hi @yue9944882, are you using the (just released) version `0.6.0`?

**Comment by yue9944882** [comment]
mmm i was working on a random commit from master branch. let me take a shot at `0.6.0`..

**Comment by iNikem** [comment]
@yue9944882 So there is still some problem?

**Comment by trask** [comment]
Hey @yue9944882! Closing this, but please let us know if you are still experiencing an issue with this. The confusing system properties that look like env vars `JAEGER_ENDPOINT` and `JAEGER_SERVICE_NAME` should be resolved by https://github.com/open-telemetry/opentelemetry-java/issues/1408

**Pull request closed without merging**
