### PR TITLE
change rpc type in apache dubbo

### PR DESCRIPTION
**Pull request by tydhot**
At present, many users' old systems in China are using Alibaba Dubbo. RPC types here need to be distinguished, otherwise there will be some confusion in observation.
Alibaba dubbo: https://search.maven.org/search?q=a:dubbo

### CODE REVIEW

**Review by trask — COMMENTED** [review]
hey @tydhot@ let's try to get this into the specification

I just opened https://github.com/open-telemetry/opentelemetry-specification/pull/2377 to start with. After that we can propose `rpc.system` values for Alibaba Dubbo and Apache Dubbo.

**Comment by tydhot** [comment]
@trask thanks!

**Comment by trask** [comment]
hi @tydhot, we can propose to specification now.

do you have a preference on naming?

https://github.com/open-telemetry/opentelemetry-specification/blob/057a1bc79f5cca85d0eebd0b5e5ec03c6a36cf7a/semantic_conventions/trace/rpc.yaml#L7-L21

maybe?

```
            - id: apache_dubbo
              value: 'apache_dubbo'
              brief: 'Apache Dubbo'
            - id: `alibaba_dubbo`
              value: 'alibaba_dubbo'
              brief: 'Alibaba Dubbo'
```

**Comment by tydhot** [comment]
@trask 

I think that's it. No problem :)

**Review by trask — APPROVED** [review]
thx @tydhot!

**Review by laurit — APPROVED** [review]

**Pull request merged**
