### PR TITLE
Replace tracing kafka wrappers with jdk proxies

### PR DESCRIPTION
**Pull request by laurit**
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6432

### CODE REVIEW

**Review by trask — APPROVED** [review]
👍

**Review by mateuszrzeszutek — APPROVED** [review]
Nice 👍

**Comment by trask** [comment]
@laurit any ideas why testLatestDeps didn't catch this issue?

**Comment by laurit** [comment]
@trask the kafka library instrumentation test that tests wrapping kafka consumer only calls poll on the wrapped consumer. The use case from the issue uses wrapped consumer with kafka streams, we don't have a similar test because we don't have library instrumentation for kafka streams and using just kafka library instrumentation + kafka streams won't give you working tracing.

**Pull request merged**
