### PR TITLE
Use ClassValue instead of ClassLoader -> Class weakmap since it shoul…

### PR DESCRIPTION
**Pull request by anuraaga**
…d be same thing.

Randomly noticed this - two `Class` in different `ClassLoader` would have different `ClassValue` right?

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by iNikem** [comment]
Will want @trask opinion here. It was his suggestion to use `ClassLoader` here.

**Comment by anuraaga** [comment]
@richardstartin Is that a laugh of agreement or a laugh at my naivete? :P

**Comment by richardstartin** [comment]
@anuraaga I just love to see the love for `ClassValue` spreading, it's arguably the most useful class in the JDK for people writing instrumentation and it goes all the way back to JDK7.

**Review by trask — APPROVED** [review]
> Will want @trask opinion here. It was his suggestion to use `ClassLoader` here.

this addresses the same issue, but much better implementation ❤️

**Pull request merged**
