### PR TITLE
Add missing Unroll annotations

### PR DESCRIPTION
**Pull request by laurit**

### CODE REVIEW

**Comment by iNikem** [comment]
@trask Did not we have some auto unroll or something?

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by trask — APPROVED** [review]
> @trask Did not we have some auto unroll or something?

that would be nice, but doesn't ring a bell

**Comment by mateuszrzeszutek** [comment]
If we add `@Unroll` to the `InstrumentationSpecification` it'll probably work everywhere

**Comment by laurit** [comment]
Without unroll method is run for both parameters given in where section, but in test report method is present only once and #methodName is not replaced in its name. With unroll test report has 2 method and #methodName is replaced with parameter.
@iNikem maybe you meant https://github.com/szpak/spock-global-unroll

**Comment by iNikem** [comment]
> @iNikem maybe you meant https://github.com/szpak/spock-global-unroll

Yes, I was sure we had this 🤔

**Review by iNikem — APPROVED** [review]

**Pull request merged**
