### PR TITLE
Update to gradle 7.6

### PR DESCRIPTION
**Pull request by trask**

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by laurit** [comment]
Previously we ran out of heap space only for latest dep tests https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6265. We could probably fix the failures by doing the same for regular tests also.

**Comment by trask** [comment]
still OOM with 2g, trying 3g...

**Comment by laurit** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/3879139964/jobs/6616036525
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 622854144 bytes for G1 virtual space
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Zero Based Compressed Oops mode in which the Java heap is
#     placed in the first 32GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 32GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_windows.cpp:3548), pid=6972, tid=5956
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Core dump will be written. Default location: D:\a\opentelemetry-java-instrumentation\opentelemetry-java-instrumentation\hs_err_pid6972.mdmp
#
```

**Comment by laurit** [comment]
Superseded by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7910

**Pull request closed without merging**
