### PR TITLE
Update metric descriptions to match semconv

### PR DESCRIPTION
**Pull request by trask**
Pending merging of
* https://github.com/open-telemetry/semantic-conventions/pull/275
* https://github.com/open-telemetry/semantic-conventions/pull/276

Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9478

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by breedx-splk — APPROVED** [review]

**Comment by puckpuck** [comment]
Fixes #9479

**Comment by trask** [comment]
HTTP descriptions resolved by #9635, planning to send another update for RPC metric descriptions to semconv repo anyways

**Comment by garg031** [comment]
Hello @trask,

I see you have fixed the description issue at - https://github.com/open-telemetry/semantic-conventions/pull/275

However we are using https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.1/opentelemetry-javaagent.jar

Do we plan to fix same issue in opentelemetry-java-instrumentation also ?

**Comment by garg031** [comment]
> Hello @trask,
> 
> I see you have fixed the description issue at - [open-telemetry/semantic-conventions#275](https://github.com/open-telemetry/semantic-conventions/pull/275)
> 
> However we are using https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.1/opentelemetry-javaagent.jar
> 
> Do we plan to fix same issue in opentelemetry-java-instrumentation also ?

Any reson why this PR was not merged ?

**Comment by trask** [comment]
hi @garg031, is this still an issue in the latest 2.7.0 version?

**Pull request closed without merging**
