### PR TITLE
Fix rxjava2 NoSuchFieldError

### PR DESCRIPTION
**Pull request by laurit**
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2819

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]
`TracingConditionalSubscriber` and `TracingSubscriber` seem to suffer from the same problem - could you update them too?
Thanks!

**Comment by laurit** [comment]
@mateuszrzeszutek they have a different super class where the field wasn't renamed. I guess this is because in there `qs` has type `QueueSubscription` but in `BasicFuseableObserver` it is `QueueDisposable`. Unless I missed something they should work as they are.

**Comment by mateuszrzeszutek** [comment]
Oh, that's great then -- I just remembered that I had to change those two the last time I was dealing with field renames (`actual` -> `downstream`)

**Review by trask — APPROVED** [review]
thx!

**Pull request merged**
