### PR TITLE
Remove armeria notice from logback instrumentation library.

### PR DESCRIPTION
**Pull request by vovencij**
There doesn't seem to be any modified parts of armeria in logback instrumentation library, as this NOTICE.txt claimed.

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Oops think I copy-paste-fudged

**Comment by vovencij** [comment]
Is there anything I can do with the build failure, besides asking code owners to trigger a rebuild?
```
Post job cleanup.
Save gradle-generated-jars
Save local-build-cache
Save dependencies-gradle
  /home/runner/work/_actions/burrunan/gradle-cache-action/v1.6/dist/cache-action-entrypoint.js:33384
            throw new Error("Cache upload failed because file read failed with " + error.message);
            ^
  
  Error: Cache upload failed because file read failed with ESPIPE: invalid seek, read
      at ReadStream.<anonymous> (/home/runner/work/_actions/burrunan/gradle-cache-action/v1.6/dist/cache-action-entrypoint.js:33384:17)
      at ReadStream.emit (events.js:210:5)
      at internal/fs/streams.js:167:12
      at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by anuraaga** [comment]
That's an annoying flake :( But as a general comment, it's generally possible to use an effectively no-op amend commit + force push to trigger the build. It's what I do for repos I don't have access to.

**Comment by anuraaga** [comment]
After rerunning it went green so went ahead and hit it! Thanks @vovencij and sorry for the troubles.

**Pull request merged**
