### PR TITLE
WIP  - changes to markdown file

### PR DESCRIPTION
**Pull request by SivaTharun**
Connects #2891  

Notes

- Added the documentation to clarify the support for multi version folder struture

- Added a note section to address the same

### CODE REVIEW

**Review by trask — COMMENTED** [review]
hey @SivaTharun!

have a look at the directory structure under `instrumentation/okhttp/`, I think that's probably the best example to help you 👍

**Comment by iNikem** [comment]
> hey @SivaTharun!
> 
> have a look at the directory structure under `instrumentation/okhttp/`, I think that's probably the best example to help you 👍

@SivaTharun, do you plan to continue working on this PR? If not, I will close this draft :)

**Comment by SivaTharun** [comment]
@iNikem yes,  i will work on this PR, i will  convert the DRAFT to PR, in a day or two.

**Comment by iNikem** [comment]
@SivaTharun I am doing the next round of cleanups, are you still interested in this PR?

**Comment by trask** [comment]
Closing just to groom the PR backlog, but we can definitely re-open at any point.

**Pull request closed without merging**
