### PR TITLE
Use + instead of printf in logging exporter

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

Created from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1246#discussion_r494045579

@trask @iNikem is there any reason why the agent is not using the logging exporter from the SDK? The only difference is that SDK uses JUL and agent directly stdout.

cc) @anuraaga

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
If I recall correctly it was for some Agent-y reason @trask mentioned once but can't remember exactly.

**Comment by anuraaga** [comment]
Ah also FYI re: StringBuilder. Concatenation and SB are currently equivalent because we compile to Java 8. But Java 9+ have optimized it further so I generally recommend sticking with append so (hopefully in another 15 years or so at the current rate of JVM upgrades...) when compiling against a new Java we get the perf for free.

**Comment by iNikem** [comment]
JUL is complicated for javaagent, especially on WildFly and other JBosses.

**Review by trask — APPROVED** [review]

**Comment by trask** [comment]
hey @pavolloffay, looks like this needs a `spotlessApply`

**Comment by pavolloffay** [comment]
done

**Comment by pavolloffay** [comment]
Can somebody restart the `build_test_deploy` job?

**Comment by trask** [comment]
hey @pavolloffay, it's failing due to #1258, i'll ping you on this PR once that's fixed and then you can rebase and it should pass

**Comment by trask** [comment]
master is fixed now 👍

**Pull request merged**
