### PR TITLE
fix: invalid semantic conventions doc url fix

### PR DESCRIPTION
**Pull request by xiangtianyu**
semantic conventions doc has moved to new repo or directory, so the old url are invalid, update these doc urls

### CODE REVIEW

**Review by steverao — COMMENTED** [review]
It seems you only fixed a part of them, maybe you can use the keyword of `semantic_conventions` to find all relevant problems and fix all this time.

**Comment by xiangtianyu** [comment]
> It seems you only fixed a part of them, maybe you can use the keyword of `semantic_conventions` to find all relevant problems and fix all this time. image

The other matches are in changelog or like such url include specific version "https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/instrumentation/aws-sdk.md"

**Comment by steverao** [comment]
> > It seems you only fixed a part of them, maybe you can use the keyword of `semantic_conventions` to find all relevant problems and fix all this time. image
> 
> The other matches are in changelog or like such url include specific version "https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/instrumentation/aws-sdk.md"

It will be better to fix invalid url in changelog instead of ignoring it. After fixing it, we may need to update relevant [release note](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.13.0) again. cc @open-telemetry/java-instrumentation-approvers

**Comment by xiangtianyu** [comment]
> > > It seems you only fixed a part of them, maybe you can use the keyword of `semantic_conventions` to find all relevant problems and fix all this time. image
> > 
> > 
> > The other matches are in changelog or like such url include specific version "https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/instrumentation/aws-sdk.md"
> 
> It will be better to fix invalid url in changelog instead of ignoring it. After fixing it, we may need to update relevant [release note](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.13.0) again. cc @open-telemetry/java-instrumentation-approvers

We may change these changelog urls to such such url include specific version "https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/metrics/semantic_conventions/runtime-environment-metrics.md"? Or to the new repo?

**Review by laurit — APPROVED** [review]

**Pull request merged**
