### PR TITLE
Add logback.xml to testing-common

### PR DESCRIPTION
**Pull request by anuraaga**
Adapted from the first one I clicked through to, https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/aws-sdk-1.11/javaagent/src/test/resources/logback-test.xml

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Review by iNikem — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by laurit** [comment]
Should we also add `testLogging.showStandardStreams = true`?

**Comment by trask** [comment]
> Should we also add `testLogging.showStandardStreams = true` or whatever the incantation is to get full test output from gradle.

It looks like this may have made the build log large and hard to find failure.

**Comment by anuraaga** [comment]
Good call out. Will leave the xml and add a property to make it easier to activate logging locally

**Comment by iNikem** [comment]
@anuraaga are you still interested in this PR?

**Comment by iNikem** [comment]
@anuraaga ping

**Review by anuraaga — COMMENTED** [review]
Thanks @trask

**Pull request merged**
