### PR TITLE
Disable context propagation when virtual thread is switched to the carrier thread

### PR DESCRIPTION
**Pull request by laurit**
Hopefully resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10747

### CODE REVIEW

**Review by JonasKunz — APPROVED** [review]
Solution looks great to me!
I still had no lock with trying to reproduce the issue though...

**Comment by Moscagus** [comment]
I can reproduce the nested parking problem.
If there is a new snapshot I can try it.
Very good solution to avoid context propagation when there is a switch to carrier thread !!!

**Comment by Moscagus** [comment]
First I'm going to review your changes.
It is difficult for me to test all the time in production.
Minimally I want to take a look at its changes.

**Review by trask — APPROVED** [review]

**Comment by Moscagus** [comment]
@laurit  after several consecutive tests I confirm that the solution does not work.
[jcmd.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/14616956/jcmd.txt)
[jstack.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/14616957/jstack.txt)

I keep investigating

**Comment by Moscagus** [comment]
@laurit the investigation was always based on the latest version of "VirtualThread.java"
https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/VirtualThread.java
The signatures are:
private void switchToCarrierThread()
private void switchToVirtualThread(VirtualThread vthread)

But in java 21+13:
https://github.com/openjdk/jdk/blob/jdk-21%2B13/src/java.base/share/classes/java/lang/VirtualThread.java
The signatures are:
private boolean switchToCarrierThread()
private void switchToVirtualThread(VirtualThread vthread, boolean notifyJvmti)

Maybe for this reason the "advices" in "VirtualThreadInstrumentation" are never executed.

**Pull request merged**
