### PR TITLE
Feature: Init GCP exporter

### PR DESCRIPTION
**Pull request by AlexanderMann**
# Motivation

In wanting exporter to GCP Trace, trying to follow up with first steps to get things moving along!

## Suggested Musical Pairing

https://www.youtube.com/watch?v=pFtk274nHX4&t=0s

### CODE REVIEW

**Comment by trask** [comment]
Hi @AlexanderMann, thanks for the PR! unfortunately we're not hosting any vendor-specific exporters here (none of the OpenTelemetry projects are), so this will need to be hosted by Google

cc: @james-bebbington

**Comment by anuraaga** [comment]
@AlexanderMann Thanks for the work on this, the code itself looks great. Perhaps you can move this to a PR on https://github.com/GoogleCloudPlatform/opentelemetry-operations-java ?

**Comment by AlexanderMann** [comment]
Happy to!

To get access to the necessary classes (`io.opentelemetry.javaagent.tooling.exporter.SpanExporterFactory`, etc.), is it recommended to depend on this lib? Should I be excluding certain packages etc. when I do? Are there plans to move those more base classes etc. over to the `sdk`?

**Comment by AlexanderMann** [comment]
@trask in case notifications are burried for you ^

**Comment by AlexanderMann** [comment]
Found this bit: https://github.com/newrelic/opentelemetry-exporter-java/compare/v0.8.0...main#diff-df37769e469d0c37211ca56acbc10db7R11

Closing here in favour of: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/39

**Pull request closed without merging**
