### PR TITLE
Add resource providers

### PR DESCRIPTION
**Pull request by jack-berg**
Related to [#4701](https://github.com/open-telemetry/opentelemetry-java/issues/4701).

Note, if merged as is this will publish with 1.18.0. Perhaps we should wait until 1.19.0?

Also, this artifact was stable in `opentelemetry-java` but is currently alpha here. We should discuss whether we want to mark it as stable.

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]
After this PR gets merged (in its current shape), the agent will still depend on the old resource modules, and these new resource providers will not be included in it by default -- and I'm completely fine with that, we can change that in the next PR, I just wanted to state that openly so that we're all on the same page here.

**Comment by jack-berg** [comment]
> After this PR gets merged (in its current shape), the agent will still depend on the old resource modules, and these new resource providers will not be included in it by default 

Yes I was planning on doing that in a followup. Happy to do it in this PR to if you prefer.

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by trask** [comment]
@jack-berg I maybe didn't follow, any reason not to include in 1.18.0?

**Comment by jack-berg** [comment]
Only reason to hold off might be so there aren't two undeprecated versions of these resource providers published in 1.18.0. I.e. `io.opentelemetry:opentelemetry-sdk-extension-resources:1.18.0` and `io.opentelemetry.instrumentation:opentelemetry-resources:1.18.0-alpha` would both have the same code and both be undeprecated. 

I don't feel strongly about this though. Can also merge with a flag that disabled publishing until post release.

**Comment by trask** [comment]
got it, thx, that makes sense, will hold on this until after 1.18.0 release

**Pull request merged**
