### PR TITLE
Add endpoint.peer.service.mapping property to allow a user to specify…

### PR DESCRIPTION
**Pull request by anuraaga**
… mappings from an endpoint to a service name and use it to map exported spans to a service name.

For #555

### CODE REVIEW

**Comment by anuraaga** [comment]
I went ahead and added the business logic too in case it helps with more context (it probably does for another issue I'm working on anyways :) ).

**Comment by anuraaga** [comment]
Chatted with @trask and he suggested that we move the logic into a decorator and try it out.

**Comment by trask** [comment]
@anuraaga can u check the test failures? looks like they are of the non-sporadic variety 😄

**Comment by anuraaga** [comment]
@trask Might need some help, have stared a while but can't for the life of me figure out what's wrong with the tests for the subclass of `BaseDecoratorTest`.

Step debugging in IntelliJ the assertions seem to work, but the unit test output from Gradle looks strange.

`BaseDecoratorTest` - has 4 executions of each of the `onPeerConnection tests`
```
Test | Duration | Result
-- | -- | --
test afterStart | 0.001s | passed
test assert null span | 0.001s | passed
test beforeFinish | 0s | passed
test onError[0] | 0s | passed
test onError[1] | 0s | passed
test onPeerConnection with mapped peer[0] | 0.001s | passed
test onPeerConnection with mapped peer[1] | 0s | passed
test onPeerConnection with mapped peer[2] | 0s | passed
test onPeerConnection with mapped peer[3] | 0s | passed
test onPeerConnection[0] | 0.001s | passed
test onPeerConnection[1] | 0.001s | passed
test onPeerConnection[2] | 0.001s | passed
test onPeerConnection[3] | 0s | passed
test spanNameForMethod[0] | 0s | passed
test spanNameForMethod[1] | 0s | passed
test spanNameForMethod[2] | 0s | passed
```

`ClientDecoratorTest` - Only has one
```

Test | Duration | Result
-- | -- | --
test afterStart | 0.036s | passed
test afterStart[0] | 0.002s | passed
test afterStart[1] | 0.001s | passed
test afterStart[2] | 0s | passed
test assert null span | 0.001s | passed
test beforeFinish | 0s | passed
test beforeFinish | 0.001s | passed
test currentContextWith | 0.001s | passed
test getOrCreateSpan internal after client span | 0.012s | passed
test getOrCreateSpan when existing client span | 0.008s | passed
test getOrCreateSpan when no existing client span | 0.017s | passed
test onError | 0.009s | passed
test onPeerConnection | 5.186s | passed
test onPeerConnection with mapped peer | 0.029s | failed
test spanNameForMethod | 0.031s | passed
```

Any pointers to what might be missing? It seems like an interaction of spock + subclass but not sure.

**Comment by trask** [comment]
hey, looks like there's a `span` field in the subclasses also, and for some reason (???) if you reference `span` in the base class inside of a closure, it picks up the `span` from the subclass:

<pre>
    ConfigUtils.withConfigOverride(
      "endpoint.peer.service.mapping",
      "1.2.3.4=catservice,dogs.com=dogsservice,opentelemetry.io=specservice") {
      decorator.onPeerConnection(<b>span</b>, connection)
    }
</pre>

anyways, delete the `span` field in the subclasses i think will resolve (and keep others from hitting this)

**Comment by anuraaga** [comment]
Thanks - crazy behavior, and crazy debugging skills!

**Pull request merged**
