### PR TITLE
Capture MethodRequest in Context to derive Reactor checkpoint

### PR DESCRIPTION
**Pull request by HaloFour**
Refactors aspect instrumentation so that the request implements a common interface `MethodRequest` which is added to the `Context`.  The `ReactorAsyncOperationEndStrategy` can then extract the `MethodRequest` and use it to get the name of the span in order to create a Reactor checkpoint.

### CODE REVIEW

**Comment by iNikem** [comment]
@HaloFour do you intend to finish this PR? Or should we close it to cleanup out list of PRs?

**Comment by HaloFour** [comment]
@iNikem 

I would like to continue this branch but if you'd prefer I can close this PR and resubmit once I clean it up.  Same goes for #3751.

**Comment by iNikem** [comment]
If you plan to continue working on this, then no problem, let it live :)

**Comment by trask** [comment]
same for this one

> hi @HaloFour! any objection to closing this (just trying to clean up the backlog a little), and you can re-open when you start working on it again? I think if I close it you won't be able to re-open it, but if you close it, I think you will be able to re-open yourself. And of course you can always ping on the closed PR and one of us will re-open it if that fails.

**Comment by trask** [comment]
Closing, but please ping back if you start working on it again and would like it to be re-opened!

**Pull request closed without merging**
