### PR TITLE
add jvm daemon threads instrumentation

### PR DESCRIPTION
**Pull request by tuhao1020**
Signed-off-by: HaoTu <haotu@alauda.io>

### CODE REVIEW

**Comment by trask** [comment]
I wonder if this would make sense as a boolean `daemon` attribute (dimension) on `process.runtime.jvm.threads.count`?

cc @jack-berg @jonatan-ivanov

**Comment by jack-berg** [comment]
I think that makes a lot of sense @trask. Can compute daemon vs. non-daemon with:

- daemon: `ThreadMXBead#getDaemonThreadCount()`
- non-daemon: `ThreadMXBead#getThreadCount() - ThreadMXBead#getDaemonThreadCount()`

**Comment by jonatan-ivanov** [comment]
I agree, especially because that way it is easy to aggregate the daemon + non-daemon threads.

**Comment by tuhao1020** [comment]
@trask @jack-berg  @jonatan-ivanov  Expect the following？
```
process.runtime.jvm.threads.count{daemon=true} 2
process.runtime.jvm.threads.count{daemon=false} 5
```

**Comment by jonatan-ivanov** [comment]
Yes, if you have 7 threads, 2 of them are daemon and 5 of them are not.

**Comment by tuhao1020** [comment]
@trask 
```
FILE: ./docs/supported-libraries.md
ERROR: 1 dead links found!
  [x] https://www.ibm.com/cloud/websphere-application-server → Status: 404
```

**Comment by tuhao1020** [comment]
@trask @jack-berg  @jonatan-ivanov  Can anyeone help to review the code?

**Pull request closed without merging**
