### PR TITLE
[enhance] Support `Apache Pulsar` client(version 2.8.0 to lasted)

### PR DESCRIPTION
**Pull request by tjiuming**
Fix: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2107

Motivation:

Add apache-pulsar client support

### CODE REVIEW

**Comment by tjiuming** [comment]
Tests to be completed.

**Comment by dao-jun** [comment]
> Tests to be completed.

There are some known bugs, I'll close this pr and create another pr

**Comment by dao-jun** [comment]
> Tests to be completed.

There are some known bugs, I'll close this pr and create another pr

**Comment by tjiuming** [comment]
> There are some known bugs, I'll close this pr and create another pr

There are some known bugs, I'll close this pr and create another pr

**Pull request closed without merging**
