### PR TITLE
Instrumenter SpanOmitter

### PR DESCRIPTION
**Pull request by LikeTheSalad**
An approach to allow suppressing Spans for an Instrumenter instance.

Example usage:

```java
SpanOmitter omitter = ...

Instrumenter.<String, String>builder(OpenTelemetry, "test", request -> "test span")
  .addSpanOmitter(omitter)
  .buildInstrumenter();
```

The provided `SpanOmitter`s allow to either continue with the Span creation or not, and their decision can be changed at any point at runtime. This is useful to allow for remote config instrumentation filtering for example.

By the way, I think `SpanSuppressor` could have been a better name but it was already taken.

### CODE REVIEW

**Comment by trask** [comment]
what is your specific use case? (because we have a couple different alternative solutions floating around, e.g. https://github.com/open-telemetry/opentelemetry-java/issues/6197)

> By the way, I think `SpanSuppressor` could have been a better name but it was already taken.

Would `SpanSuppressor` solve your use case if we made that class public?

**Comment by laurit** [comment]
I don't get this. `SpanSuppressor` is used to suppress nested spans for the same semconv/kind. So if you have a high level http client that uses a low level library, such as netty, the span created by the instrumentation for the high level client will suppress the one from the low level client and you don't end up with 2 spans for the same http call. In the PR description you say

> The provided SpanOmitters allow to either continue with the Span creation or not, and their decision can be changed at any point at runtime. This is useful to allow for remote config instrumentation filtering for example.

Would replacing https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/34e0eb67da467be80e5ff67d64c55963ff4015ab/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/Instrumenter.java#L80 with `BooleanSupplier` or `Predicate` satisfy this?
If you want to suppress span creation this way I'd imagine that toggling it per `Instrumenter` by adding a `SpanOmitter` isn't the most convenient way. Perhaps it would make sense to have a global predicate that is applied to all instrumenters that based on the instrumentation name, span kind, context etc. decides whether span should be created? This way you wouldn't need to separately modify instrumenters to have them participate in this. You could have rules that say drop all `INTERNAL` spans or drop all spans from okhttp instrumentation and modify these at runtime.

**Comment by LikeTheSalad** [comment]
Update: I think by using the `enabled` flag it should work, although we're still going to need to add some changes as you mentioned @laurit, to provide some sort of supplier for it when building the Instrumenter. I'll bring this up in today's SIG and, if no objections, I can create a PR for that approach.

**Comment by LikeTheSalad** [comment]
Closing this issue as these changes are no longer needed.

**Pull request closed without merging**
