### PR TITLE
Add support for apache shenyu (#5629)

### PR DESCRIPTION
**Pull request by HessTina-YuI**

### CODE REVIEW

**Comment by HessTina-YuI** [comment]
I will add test module.

**Comment by trask** [comment]
hi @HessTina-YuI! let us know if you are ready for this to be reviewed, or you can also convert it to "draft" and later mark it ready for review

**Comment by HessTina-YuI** [comment]
hi @trask ! I'm ready to be reviewed.

**Review by trask — COMMENTED** [review]
thx @HessTina-YuI! can you add some tests?

**Comment by HessTina-YuI** [comment]
hi @trask , i try to add som tests

**Comment by trask** [comment]
Closing, but please ping back if you start working on it again and would like it to be re-opened!

**Pull request closed without merging**
