### PR TITLE
Add otlp http exporters

### PR DESCRIPTION
**Pull request by trask**
So that `OTEL_EXPERIMENTAL_EXPORTER_OTLP_PROTOCOL=http/protobuf` will work once we pull in Java SDK 1.6.0 which introduces autoconfigure support for this https://github.com/open-telemetry/opentelemetry-java/pull/3522

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Comment by anuraaga** [comment]
Oh btw I think we'll need to force the okhttp dependency to avoid pulling in the kotlin stdlib (assuming we didn't accidentally pull it in elsewhere again :P). Though with it EoL, it's too bad really, I think we may need to reconsider using okhttp @jkwatson. Kotlin stdlib is just too heavyweight for a telemetry exporter I think

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by jkwatson** [comment]
> Oh btw I think we'll need to force the okhttp dependency to avoid pulling in the kotlin stdlib (assuming we didn't accidentally pull it in elsewhere again :P). Though with it EoL, it's too bad really, I think we may need to reconsider using okhttp @jkwatson @jack-berg . Kotlin stdlib is just too heavyweight for a telemetry exporter I think

Which EOL are you referring to, exactly here?

**Comment by jkwatson** [comment]
> > Oh btw I think we'll need to force the okhttp dependency to avoid pulling in the kotlin stdlib (assuming we didn't accidentally pull it in elsewhere again :P). Though with it EoL, it's too bad really, I think we may need to reconsider using okhttp @jkwatson @jack-berg . Kotlin stdlib is just too heavyweight for a telemetry exporter I think
> 
> Which EOL are you referring to, exactly here?

oh, I get it. okhttp 3.x didn't depend on the kotlin stdlib, but has been eol'd. 4.x does depend on the kotlin stdlib, which is definitely some significant bloat.

**Comment by jkwatson** [comment]
> Oh btw I think we'll need to force the okhttp dependency to avoid pulling in the kotlin stdlib (assuming we didn't accidentally pull it in elsewhere again :P). Though with it EoL, it's too bad really, I think we may need to reconsider using okhttp @jkwatson @jack-berg . Kotlin stdlib is just too heavyweight for a telemetry exporter I think

We should probably build an multi-version jar, and use the java11 httpclient if it's available. Maybe using HttpUrlConnection (ugh!) for java 8.

**Comment by trask** [comment]
> I think we'll need to force the okhttp dependency to avoid pulling in the kotlin stdlib

thx for this 👍

going to merge this now that https://github.com/open-telemetry/opentelemetry-java/pull/3590 is merged

**Pull request merged**
