### PR TITLE
Ported JMS 1.x tests to testcontainers

### LINKED ISSUE #1206: Flaky test - :instrumentation:jms-1.1:test
I've seen this test fail a lot lately - it does get retried but fails every one of them from what I can tell.

https://gradle.com/s/geylzhj6543j2

### PR DESCRIPTION
**Pull request by iNikem**
Fixes #1206

### CODE REVIEW

**Comment by iNikem** [comment]
I have a suspicion that build fails due to `AdditionalLibraryIgnoresMatcher` and static configs. And I still don't understand why do we need `AdditionalLibraryIgnoresMatcher` :(

**Comment by iNikem** [comment]
Yes, CiMate shows nicely that failure is due to `AdditionalLibraryIgnoresMatcher`. @trask can you remind me, why do we need this matcher and this strange check in our tests?

**Comment by tylerbenson** [comment]
The `AdditionalLibraryIgnoresMatcher` is intended as an optimization for startup to try to bypass a significant amount of classes we know we won't instrument.  It's handled a bit differently from other ignores in the tests because if we do happen to instrument something that matches it in a test, then something changed and we need to update the matcher.

**Review by trask — APPROVED** [review]
Nice, let the testcontainers migration start 🎉

**Comment by trask** [comment]
Interesting, the muzzle matrix was picked up in this PR even though we didn't merge that change in from master, is that normal?

**Review by anuraaga — APPROVED** [review]

**Pull request merged**
