### PR TITLE
capture mongodb database name as mongo-db.name attribute instead of client description

### PR DESCRIPTION
**Pull request by imavroukakis**
Closes https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1376

### CODE REVIEW

**Comment by imavroukakis** [comment]
It should probably be discussed what is to be done with the client description and a sensible fallback when a dbName doesn't exist. 

Client Description: Should it be added to `SemanticAttributes`?
Empty/Null database name: Client description might not be a sensible fallback, is returning `null` acceptable?

**Review by iNikem — APPROVED** [review]
If `db.name` is not available, then it is totally Ok to return `null`. What else can we do? I even think we can remove the current fallback to description.

**Comment by imavroukakis** [comment]
> If `db.name` is not available, then it is totally Ok to return `null`. What else can we do? I even think we can remove the current fallback to description.

Makes sense. Should client description also be captured if available? That would be outside the scope of this PR, but would be good to get an opinion.

**Comment by iNikem** [comment]
> Should client description also be captured if available?

If some MongoDB user thinks that this information is useful, then yes. _After_ the corresponding PR to the spec :)

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by trask — APPROVED** [review]
Thanks @imavroukakis!

**Pull request merged**
