### PR TITLE
Propagate client span context in doOnRequest

### PR DESCRIPTION
**Pull request by jamesmartinpp**
Copy of #6571 issued by @mikeweisskopf

Currently the code is propagating the PARENT span in reactor.netty.http.client.HttpClient doOnRequest, however that means that any other code written in doOnRequest hook can not access the CLIENT span. I makes sense that code written in that method would want access to the CLIENT span and not the PARENT span. For example, if you wanted to enrich that span or create a child. I have spoken with @mateuszrzeszutek and reviewed code behavior regarding this issue and PR.

@mateuszrzeszutek please review and approve.

### CODE REVIEW

**Comment by jamesmartinpp** [comment]
@mateuszrzeszutek it appears I cannot even use Mike's commit in a new PR. If needed I can redo his changes which are very small

**Comment by trask** [comment]
> If needed I can redo his changes which are very small

yes please 👍

**Comment by jamesmartinpp** [comment]
I reverted Mike's commit and redid the two line change from scratch but still it complains even though I have done the easyCLA document signing procedure. @trask do I need to close this PR because Mike's commit is still detected somehow?

**Comment by laurit** [comment]
@jamesmartinpp using a revert commit isn't enough it should be completely removed from history. Either start with a fresh pr on a new branch or try something like `git reset HEAD~3` this should get rid of the last 3 commits and preserve the changes so you can commit them again and force push.

**Comment by jamesmartinpp** [comment]
thanks @laurit . I will close this one and try again.

**Comment by jamesmartinpp** [comment]
closing to avoid issues with EasyCLA check.

**Pull request closed without merging**
