### PR TITLE
Remove inner class imports; avoid future imports by disabling in editorconfig

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by trask — APPROVED** [review]
Thanks!

**Comment by bogdandrutu** [comment]
@trask I also tested, by simply removing the import and press "option + enter" on MacOs which instead of importing the inner class (as it does without the change) was simply adding the "x.".

**Comment by trask** [comment]
👍 even if we decide to go with `XBuilder`, this will still help with guava imports (and `Map.Entry`)

**Review by anuraaga — APPROVED** [review]
Nice, thanks!

**Comment by bogdandrutu** [comment]
@trask that is the official jdk not guava that has Map.
Entry

**Pull request merged**
