### PR TITLE
Validate gradle wrapper only when changed

### PR DESCRIPTION
**Pull request by iNikem**
No need to run it on every PR

### CODE REVIEW

**Comment by iNikem** [comment]
I can add `push` with same path restriction. But I thought we have protected main branch?

**Comment by jkwatson** [comment]
> I can add `push` with same path restriction. But I thought we have protected main branch?

Can't maintainers still push to the main branch?

Adding push seems reasonable, though. Is this a very time consuming check?

**Comment by iNikem** [comment]
Nay, very fast. It just annoys my GitHub inbox :)

**Review by anuraaga — APPROVED** [review]
Change LGTM but

> Nay, very fast. It just annoys my GitHub inbox :)

Do you get GitHub notifications for successful workflows too? Seems like a lot of noise :)

**Review by trask — APPROVED** [review]

**Pull request merged**
