### PR TITLE
Simplify getting started doc

### LINKED ISSUE #310: Remove version string from "final" jar
Since our users have to modify startup scripts, config files, etc. to add the -javaagent:/path/to/our.jar parameter, we should be nice to them and only require them to touch that stuff once.  Instead of naming our jar "opentelemetry-auto-0.2.1.jar", it should just be "opentelemetry-auto.jar".  That way they can upgrade to a new version without changing scripts/config files/etc (or introducing secondary complexities like variable names holding the latest version name, etc.).

### PR DESCRIPTION
**Pull request by trask**
Just floating the idea.

For this to work, we would need to remove the version from the filename before uploading `opentelemetry-auto-all.jar` to the github release.

Would close #310

### CODE REVIEW

**Comment by iNikem** [comment]
As a note, one of the benefits of Bintray as opposed to GitHub releases is download statistics: https://bintray.com/open-telemetry/maven/opentelemetry-java-instrumentation#statistics

**Comment by trask** [comment]
github releases have download stats also:

https://api.github.com/repos/open-telemetry/opentelemetry-java-instrumentation/releases

here's a nice UI someone built on top of the REST endpoint:

   https://somsubhra.com/github-release-stats/?username=open-telemetry&repository=opentelemetry-java-instrumentation

**Comment by iNikem** [comment]
And just got answer from JFrog, that "latest version" download, without specific version number in it, is available only for Bintray Premium repositories. So indeed, it seems that referencing GitHub from our docs is simpler :(

**Comment by iNikem** [comment]
But if we merge this now, will those links work?

**Comment by trask** [comment]
see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/310#issuecomment-644481514

> using the "latest" download url requires not marking our releases as "pre-release", but i think that's ok since the point of marking releases as "pre-release" is so that they don't hide the latest release

**Pull request merged**
