### PR TITLE
Use develocity cache connector

### PR DESCRIPTION
**Pull request by laurit**

### CODE REVIEW

**Review by breedx-splk — APPROVED** [review]
Looks like this is in response to the notification we got from a person with Gradle Enterprise in regard to the build cache being disabled due to errors. Their recommendation was to use this develocity cache connector.

**Comment by breedx-splk** [comment]
There was mention that the key needs to be in the `ci-agent` role. Do we know if that's been validated?

**Review by trask — APPROVED** [review]
do we still use `GE_CACHE_USERNAME` and `GE_CACHE_PASSWORD` anywhere?

**Comment by laurit** [comment]
> do we still use `GE_CACHE_USERNAME` and `GE_CACHE_PASSWORD` anywhere?

if this works then as far as I know we won't be using these anywhere (after we backport to 1.x branch)

**Pull request merged**
