### PR TITLE
Allow to install only one MetricExporter

### PR DESCRIPTION
**Pull request by vadeg**
Allow to install only one MetricExporter

Fixes: #1353

### CODE REVIEW

**Review by trask — APPROVED** [review]
Thanks!

**Comment by iNikem** [comment]
Can you please add a test as well?

**Comment by vadeg** [comment]
@iNikem sure

**Comment by iNikem** [comment]
@vadeg Any update on this? :)

**Comment by vadeg** [comment]
@iNikem yes. I will update it this week. The implementation seems not test friendly.

**Comment by iNikem** [comment]
Was superseded by new configuration story.

**Pull request closed without merging**
