### PR TITLE
#7274 Reduce mem consumption from reference queue

### PR DESCRIPTION
**Pull request by Iapetus999**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7274

An alternative would be to create a env flag for this.

### CODE REVIEW

**Comment by trask** [comment]
hi @lapetus999! check out #6240, I believe it's addressing the same issue, and probably we should get that merged?

**Comment by Iapetus999** [comment]
Yeah we've been having a lot of problems with this. I'm okay with closing this as a dupe of the other PR. What needs to be done to get the other PR merged?

**Comment by trask** [comment]
> Yeah we've been having a lot of problems with this. I'm okay with closing this as a dupe of the other PR. What needs to be done to get the other PR merged?

great, since you have an active repro, can you build and test that PR to confirm things look good for you?

**Comment by Iapetus999** [comment]
Since the issue only repros in Production, I won't be able to test it until next week (holiday code freeze). I am running this PR and it's looking good.

**Comment by trask** [comment]
> Since the issue only repros in Production, I won't be able to test it until next week (holiday code freeze)

that would be great, the next release (1.21.0) is targeted for December 14

**Comment by trask** [comment]
I think we can close this, now that #6240 has been merged, thx for raising this!

It would still be really helpful if you could report back your findings after you have a chance to test the latest snapshot build: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/CONTRIBUTING.md#snapshot-builds

**Comment by Iapetus999** [comment]
Hi @trask 
We've had this running in Production for a few days now and it's looking good.
I grabbed `opentelemetry-javaagent-1.21.0-20221206.081659-86.jar`

**Comment by trask** [comment]
@Iapetus999 thx! 1.21.0 release should be out in a couple of days

**Pull request closed without merging**
