### PR TITLE
Remove final from local variables

### PR DESCRIPTION
**Pull request by heyams**
Fix [#592](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/592).

### CODE REVIEW

**Comment by anuraaga** [comment]
@heyams Thanks a lot for helping with this! Can you describe your approach? IntelliJ has an automated fix for unnecessary final

Help -> Find Action -> Run Inspection By Name -> Unnecessary final on local variable or parameter

You can use Fix All to have it automatically fix. Then just `./gradlew spotlessApply` will reformat and the change should be good to go.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/732/commits/821e18ababcbad949cda122f97cb771980ed3aa5 makes me nervous that you may be doing this manually, meaning there's chance of manual error.

**Comment by heyams** [comment]
@anuraaga Oops, I wasn't aware there was an automatic way to fix this.  I did it manually 😢

**Comment by heyams** [comment]
@anuraaga I can create a separate PR using your suggestion to see if it will fix all the local variables except those accessed by the inner classes.

**Comment by anuraaga** [comment]
I don't think you need to create a separate PR - how about running that on this PR. It may catch anything you missed, or otherwise it means you got them all :)

**Comment by heyams** [comment]
@anuraaga Cool, will do.  Thanks!

**Comment by heyams** [comment]
@anuraaga I missed 10 files.  Find Action works.  Thanks!

**Comment by trask** [comment]
> Help -> Find Action -> Run Inspection By Name -> Unnecessary final on local variable or parameter

Oh nice! I didn't know about this either. I need to hang around @anuraaga more :smile:

**Comment by iNikem** [comment]
> > Help -> Find Action -> Run Inspection By Name -> Unnecessary final on local variable or parameter
> 
> Oh nice! I didn't know about this either. I need to hang around @anuraaga more 😄

Take a look at videos by Trish Gee, such as this https://www.youtube.com/watch?v=9AMcN-wkspU :)

**Comment by heyams** [comment]
Thank you @anuraaga!  I saw one muzzle failed last night.. wonder what was the cause?  Do we have a group chat?  If i need to do another manual cleanup, I would like to sync up with you before doing anything... @anuraaga seems to know the magic tricks :)

**Comment by iNikem** [comment]
@heyams Official Gitter channel will do :) https://gitter.im/open-telemetry/opentelemetry-java-instrumentation

**Pull request merged**
