### PR TITLE
SpanAssert method names should reflect underlying Span method names

### PR DESCRIPTION
**Pull request by imavroukakis**
Closes https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/690

### CODE REVIEW

**Comment by anuraaga** [comment]
Thanks @imavroukakis! This looks like the right change to the API but we need to update the usage in the tests too. It's groovy, but I think IntelliJ'a rename refactoring should automatically change them. Can you try that?

**Comment by imavroukakis** [comment]
@anuraaga I'm making good progress but I'm a bit stumped by a couple of errors at `GrpcStreamingTest` and `GrpcTest`. The tests are complaining about a `MissingMethodException` at at `GrpcStreamingTest` L117 but I can't see why that would be the case. Any suggestions would be appreciated

**Comment by iNikem** [comment]
@imavroukakis Those tests have Spock data table which contribute input parameter `name`. This clashes with method called `name`. Maybe rename method to `spanName`?

**Comment by imavroukakis** [comment]
> @imavroukakis Those tests have Spock data table which contribute input parameter `name`. This clashes with method called `name`. Maybe rename method to `spanName`?

Thanks @iNikem, wouldn't have thought to look there, I've not used Spock before. Since the spirit of this PR is to have a method name equivalence between `SpanAssert` and the underlying `Span` would it make more sense to rename the Spock input parameter? If so, where should I look for it?

**Comment by imavroukakis** [comment]
> > @imavroukakis Those tests have Spock data table which contribute input parameter `name`. This clashes with method called `name`. Maybe rename method to `spanName`?
> 
> Thanks @iNikem, wouldn't have thought to look there, I've not used Spock before. Since the spirit of this PR is to have a method name equivalence between `SpanAssert` and the underlying `Span` would it make more sense to rename the Spock input parameter? If so, where should I look for it?

ignore the comment about looking for the data table, I looked it up on the Spock documentation :)

**Comment by imavroukakis** [comment]
thanks, @iNikem that got me a lot further! I've only got to figure out why the couchbase-2.6 tests are failing now.

**Comment by imavroukakis** [comment]
Tests passed and the build is green https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1307/checks?check_run_id=1199938449

I've done a force push after a rebase to tidy up the commits, @anuraaga feel free to review 😄

**Comment by trask** [comment]
hey @imavroukakis! looks like we've hit the jfrog snapshot retention issue again. I opened #1320 to track this, I'll ping back on this thread once that's fixed so you can merge master.

**Review by anuraaga — APPROVED** [review]
Thanks a lot, nice change

**Comment by trask** [comment]
@imavroukakis master is fixed now 👍

**Review by iNikem — APPROVED** [review]

**Comment by anuraaga** [comment]
Hmm CircleCI didn't run - let me try kicking it

**Comment by anuraaga** [comment]
Thanks @imavroukakis!

**Pull request merged**
