### PR TITLE
Add kafka client metrics to the javaagent instrumentation

### LINKED ISSUE #5941: Kafka-metrics
.
can we expect to have kafka metrics
1. kafka_producer_message_count
2. kafka_consumer_message_count

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
Resolves #5941

### CODE REVIEW

**Comment by trask** [comment]
Closing and re-opening to trigger latest dep tests

**Review by trask — COMMENTED** [review]
@mateuszrzeszutek are these metrics on-by-default?

**Comment by mateuszrzeszutek** [comment]
Yes, enabled by default.

**Review by laurit — APPROVED** [review]

**Comment by trask** [comment]
oh, sorry, I meant to bring this up in SIG meeting today, I was unsure whether this should be on by default or not, since these are not spec'd metrics, but I guess we're considering it to be similar to micrometer (which is enabled by default)?

one other related concern is that I didn't see an easy way to disable them (without defining a metrics view)?

**Comment by mateuszrzeszutek** [comment]
> oh, sorry, I meant to bring this up in SIG meeting today, I was unsure whether this should be on by default or not, since these are not spec'd metrics, but I guess we're considering it to be similar to micrometer (which is enabled by default)?
> 
> one other related concern is that I didn't see an easy way to disable them (without defining a metrics view)?

I think it probably makes sense to have them enabled by default, since it's a bridge/shim-like instrumentation, like micrometer. Making it easy to turn this off sounds good though, I'll add a property for disabling them 👍

**Review by jack-berg — APPROVED** [review]

**Pull request merged**
