### PR TITLE
Extract `APIGatewayProxyRequestEvent` headers for context propagation

### PR DESCRIPTION
**Pull request by cleverchuk**
Extract `APIGatewayProxyRequestEvent` headers for context propagation. This change is only added to `aws-lambda-events-2.2` package because the `aws-lambda-core` instrumentation only applies to Lambdas that use custom events.

### CODE REVIEW

**Comment by cleverchuk** [comment]
@tylerbenson @laurit

**Comment by laurit** [comment]
@cleverchuk could you update the PR title, we use PR titles in changelog.

**Review by tylerbenson — APPROVED** [review]
An additional unit test might be nice.  Not sure how much effort that would be though.

**Comment by laurit** [comment]
@cleverchuk could you see if it is possible to build a test similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/780cdf4a9358e215a32579c10d92b47d1ebbc30d/instrumentation/aws-lambda/aws-lambda-events-2.2/library/src/test/java/io/opentelemetry/instrumentation/awslambdaevents/v2_2/AwsLambdaApiGatewayWrapperTest.java#L65 that would test the functionality that you have implemented.

**Comment by cleverchuk** [comment]
@laurit @tylerbenson added a test. I don't understand entirely how the testing works though. However the test fails without the change, which I think is a good sign. This check kept failing so I removed it because I don't know how to get it to work.
 ```java
equalTo(HttpAttributes.HTTP_RESPONSE_STATUS_CODE, 201L)
```

**Review by laurit — APPROVED** [review]

**Pull request merged**
