### PR TITLE
Convert smoke tests into reusable workflow

### PR DESCRIPTION
**Pull request by trask**

### CODE REVIEW

**Review by laurit — APPROVED** [review]
the only change I'd make would be to skip running windows smoke tests for pull requests

**Comment by trask** [comment]
> the only change I'd make would be to skip running windows smoke tests for pull requests

just confirming, because they're basically redundant, or some other reason?

**Comment by laurit** [comment]
> > the only change I'd make would be to skip running windows smoke tests for pull requests
> 
> just confirming, because they're basically redundant, or some other reason?

for faster feedback, windows tests just take more time to run and the chance of breaking agent on only windows isn't too high

**Comment by trask** [comment]
👍 got it, I'm going to merge and will try that in a follow-up

**Pull request merged**
