### PR TITLE
Consolidate github action renovate PRs

### PR DESCRIPTION
**Pull request by trask**
I'm currently testing this in my fork with `schedule:daily` to see if it works...

* https://github.com/trask/opentelemetry-java-instrumentation/pulls
* https://developer.mend.io/github/trask/opentelemetry-java-instrumentation

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
This LGTM, but perhaps @secustor can give a second opinion?

**Review by secustor — APPROVED** [review]
LGTM, but it maybe helpful to consider the downsides of grouping large numbers of dependencies.
https://docs.renovatebot.com/noise-reduction/#be-smart-about-grouping-dependencies

**Comment by jpkrohling** [comment]
I agree, in this case it makes sense though: GitHub Actions have a lower risk, and it's quite clear when they break.

**Comment by secustor** [comment]
> Lately renovate created some PRs where version was update to an older version, batching the updates would make this harder to spot.

There has been an issue which we couldn't reproduce so far, but users report that a guardrail against that works. https://github.com/renovatebot/renovate/issues/29919

**Comment by trask** [comment]
> I'm currently testing this in my fork with `schedule:daily` to see if it works...
> 
> * https://github.com/trask/opentelemetry-java-instrumentation/pulls
> * https://developer.mend.io/github/trask/opentelemetry-java-instrumentation

looks like it's working: https://github.com/trask/opentelemetry-java-instrumentation/pull/3

**Review by laurit — APPROVED** [review]

**Comment by trask** [comment]
let's give it a try...

**Pull request merged**
