### PR TITLE
Add close to fix CWE-404

### PR DESCRIPTION
**Pull request by sam9291**
Hi, our security tool has detected 2 [CWE-404](https://cwe.mitre.org/data/definitions/404.html)

Add missing JarFile close to fix CWE-404
Add missing InputStream close to fix CWE-404

image
image

image
image

### CODE REVIEW

**Comment by trask** [comment]
hi @sam9291! you can ignore the test-latest-deps failures, I don't think they're related to your PR

**Comment by sam9291** [comment]
Hi @trask thanks for the feedback, before merging, I'll just need someone with a more experience than me on the context to confirm that my this change doesn't impact anything else, the fix was inspired by what was done in #1970. I don't have the proper setup to run this locally easily 😅

**Comment by trask** [comment]
can you run `./gradlew spotlessApply` locally? that should fix the spotless CI failure

**Review by trask — APPROVED** [review]
thanks!

**Pull request merged**
