### PR TITLE
Enable instrumentation of Spring EJB clients

### PR DESCRIPTION
**Pull request by zackman0010**
Spring's XML configuration allows connecting to a remote EJB through the `remote-slsb` XML element. This connection utilizes a class in the package `org.springframework.ejb.access`. This PR instruments the required class.

### CODE REVIEW

**Review by trask — COMMENTED** [review]
thanks! is it possible to add a test similar to [SpringRmiTest.groovy](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-rmi-4.0/javaagent/src/test/groovy/SpringRmiTest.groovy) for this?

**Comment by zackman0010** [comment]
Sure, I'll see what I can do!

**Comment by zackman0010** [comment]
@trask I was able to write a test for the remote-slsb Spring XML integration pattern. While I was at it, I also converted the Groovy test to Java for #7195. 
The current CI/CD failure appears to be unrelated to my changes, every commit in main from the past day has failed with the same error.

**Review by laurit — APPROVED** [review]

**Comment by zackman0010** [comment]
Thanks @laurit! I wasn't able to find a way to dynamically create an EJB at runtime, so it's cool to see that you were able to.

**Pull request merged**
