### PR TITLE
Resolve sockPeerName in case no match exists for peerName

### LINKED ISSUE #6813: Support Service Peer Name Mappings with Lettuce
**Is your feature request related to a problem? Please describe.**
Using `otel.instrumentation.common.peer-service-mapping` it is possible to get more developer friendly descriptions of contacted systems via HTTP. So for example Grafana with Tempo instead of only "HTTP GET" the name of the mapped system will be shown. Unfortunately this doesn't work for Redis with Lettuce. It might be caused by the different attribute named `net.sock.peer.name` instead of `net.peer.name` for REST.

**Describe the solution you'd like**
Would it be possible to support these mappings for Lettuce (any maybe all clients providing `net.sock.peer.name` )? I'm not sure if this mapping happens in the client implementation or on a higher level after the attributes have been generated.

**Describe alternatives you've considered**
Currently, it's okay to have only the domain names. But this feature would be nice.

**Additional context**
If you can show me the place in code where the mapping happens and aggree with this request, I could create a PR and do the work. :)

### PR DESCRIPTION
**Pull request by floric**
Closes #6813

### CODE REVIEW

**Comment by mateuszrzeszutek** [comment]
Hey @floric can you sign the CLA?

**Comment by floric** [comment]
> Hey @floric can you sign the CLA?

yes, I already contacted my company, but need to wait for the feedback. Will also fix the tests of course...

**Comment by trask** [comment]
hi @floric! I'm curious if DCO would be easier for you/your company compared to SLA, check out recent discussion going on about CLA vs DCO in the OpenTelemetry community repo: https://github.com/open-telemetry/community/issues/1252

**Comment by mxmehl** [comment]
> hi @floric! I'm curious if DCO would be easier for you/your company compared to SLA, check out recent discussion going on about CLA vs DCO in the OpenTelemetry community repo: [open-telemetry/community#1252](https://github.com/open-telemetry/community/issues/1252)

Open Source person from @floric's company here. Yes, DCO sign-offs would be **a lot** easier for us, and - depending on the 
analysis' result of the CLA - be the only possibility for employees like them to contribute to this and other CLA'd projects.

**Comment by floric** [comment]
Unfortunately, we will need to cancel this contribution because of the license for now. :/ I'm really sorry and hope, we will find a solution soon.

**Pull request closed without merging**
