### PR TITLE
fixed potential NullPointerException if AMQP.Properties::getHeaders returns null

### PR DESCRIPTION
**Pull request by bnikster**
In some applications we are not providing headers at the AMQP.Properties, which results in the following exception:
java.lang.NullPointerException\n at io.opentelemetry.javaagent.instrumentation.rabbitmq.TextMapExtractAdapter.get(TextMapExtractAdapter.java:22)\n at io.opentelemetry.javaagent.instrumentation.rabbitmq.TextMapExtractAdapter.get(TextMapExtractAdapter.java:11)\n
....

After the error RabbitMQ stopped working, these fix prevents the NullPointerException

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by mateuszrzeszutek** [comment]
Hey @bnikster ,
Can you sign the CLA?

**Comment by bnikster** [comment]
> Hey @bnikster ,
> Can you sign the CLA?

done!

**Review by iNikem — APPROVED** [review]

**Review by laurit — APPROVED** [review]

**Comment by bnikster** [comment]
@mateuszrzeszutek don't know why instrumentation:jedis fails, i did not change anything in this module. can you please check this. thank you.

**Comment by mateuszrzeszutek** [comment]
That's an unrelated issue, it's already fixed on the main branch.
Can you rebase/merge? It should fix that one failing check.

**Comment by bnikster** [comment]
@mateuszrzeszutek 

I have merged main branch now

**Pull request merged**
