### PR TITLE
Migrate some SQL sanitizer tests to java

### PR DESCRIPTION
**Pull request by breedx-splk**
Is there a way to tell spotless to ignore a file? I feel like some manual formatting would be an improvement in these....

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by breedx-splk** [comment]
> ```java
> // @formatter:off
> ```

Hmph, I tried it around a block and around the class and couldn't get it to work either way. 🤷🏻 Not a big deal.

**Comment by breedx-splk** [comment]
Build errors look maven related. I don't have perms to re-run the failed jobs.

**Comment by trask** [comment]
@breedx-splk heads up I merged main into your branch to fix the CI failures

**Review by trask — APPROVED** [review]
🥳

**Pull request merged**
