### PR TITLE
Fix context propagation for ratpack request body stream

### PR DESCRIPTION
**Pull request by laurit**
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/12317
Also disables creating ratpack server handler span by default, like we did for other instrumentations in 2.0.

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Comment by NaveenRamu** [comment]
@laurit What will be the release or snapshot version for this fix?

**Comment by laurit** [comment]
> @laurit What will be the release or snapshot version for this fix?

currently we are at `2.9.0-SNAPSHOT`

**Comment by NaveenRamu** [comment]
@laurit Can you please provide me with a link to download the SNAPSHOT version?

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/CONTRIBUTING.md#snapshot-builds

**Comment by NaveenRamu** [comment]
@laurit Thank you.

**Pull request merged**
