### PR TITLE
updates the examples/distro to use latest release

### PR DESCRIPTION
**Pull request by breedx-splk**
The examples were on the previous version, this updates to 0.14.0 agent and 0.14.1 otel-java.

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by jkwatson — APPROVED** [review]

**Review by trask — APPROVED** [review]
❤️

**Comment by anuraaga** [comment]
@breedx-splk Does the custom id generator work? I couldn't figure out a way to get it to work, hence increasing the priority of #2077

**Comment by breedx-splk** [comment]
Ooh, good point @anuraaga ...I didn't try it so I can't say for sure.  There are also deprecated usages that will need to be updated after the next release, assuming we want to keep these up to date with releases and not snaps.  🤷

**Comment by anuraaga** [comment]
@breedx-splk No worries - just making sure I didn't miss something, in which case I wouldn't need to do a patch release :P

**Pull request merged**
