### PR TITLE
Remove version from `apache-httpclient` instrumentation

### PR DESCRIPTION
**Pull request by vadeg**
Remove version from `apache-httpclient` instrumentation

Fixes: #1260

### CODE REVIEW

**Comment by trask** [comment]
Hi @vadeg, thanks for the PR!

Are you able to sign the CLA (above)?

And could you make this change for all instrumentation in this PR, so we don't end up with some instrumentation names with the version and some without the version?

**Comment by vadeg** [comment]
Hi @trask ,

Definitely. I have one question. There is [SpringWebMvcServerTracer](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/spring/spring-webmvc-3.1/library/src/main/java/io/opentelemetry/instrumentation/spring/webmvc/SpringWebMvcServerTracer.java#L76-L77) in the `spring-webmvc-3.1` project and it has no name:
```
  @Override
  protected String getInstrumentationName() {
    return null;
  }
```
Is it intentional?

**Comment by trask** [comment]
That does not look intentional.

I realized I have one doubt about the instrumentation names (I opened #1436 to discuss), but I think it's good to go ahead and remove the versions in this PR 👍.

**Comment by vadeg** [comment]
I will reopen PR. I can not accept CLA. The links redirects me to the blank page.

**Pull request closed without merging**
