### PR TITLE
Fix disabling virtual thread context propagation

### PR DESCRIPTION
**Pull request by laurit**
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10747
Continuation of https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10854

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Comment by Moscagus** [comment]
@laurit the investigation was always based on the latest version of "VirtualThread.java"
https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/VirtualThread.java
The signatures are:
private void switchToCarrierThread()
private void switchToVirtualThread(VirtualThread vthread)

But in java 21+13:
https://github.com/openjdk/jdk/blob/jdk-21%2B13/src/java.base/share/classes/java/lang/VirtualThread.java
The signatures are:
private **boolean** switchToCarrierThread()
private void switchToVirtualThread(VirtualThread vthread, **boolean notifyJvmti**)

Maybe for this reason the "advices" in "VirtualThreadInstrumentation" are never executed.

**Comment by laurit** [comment]
> @laurit the investigation was always based on the latest version of "VirtualThread.java" https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/VirtualThread.java The signatures are: private void switchToCarrierThread() private void switchToVirtualThread(VirtualThread vthread)
> 
> But in java 21+13: https://github.com/openjdk/jdk/blob/jdk-21%2B13/src/java.base/share/classes/java/lang/VirtualThread.java The signatures are: private **boolean** switchToCarrierThread() private void switchToVirtualThread(VirtualThread vthread, **boolean notifyJvmti**)
> 
> Maybe for this reason the "advices" in "VirtualThreadInstrumentation" are never executed.

I don't think so. It was never executed because by default some classes are excluded from instrumentation and I forgot to enable it for the virtual thread class.
I din't realize that `21+13` is an early access version, 2 arg `switchToVirtualThread` should be handled with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10887

**Comment by laurit** [comment]
> Can you generate a snapshot for me to test in my productive environment ?

you can find the jar in the artifacts section of the PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/8340418609 or in https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/javaagent/opentelemetry-javaagent/2.3.0-SNAPSHOT/ after the PR is merged

**Comment by Moscagus** [comment]
After several tests with 1 million virtual threads, I'm pretty sure the solution works.
Thanks @laurit

**Comment by YaoYingLong** [comment]
> After several tests with 1 million virtual threads, I'm pretty sure the solution works. Thanks @laurit

@Moscagus Is there a demo example for reproducing the issue? I encountered the same problem, but I couldn't reproduce it.

**Pull request merged**
