### PR TITLE
WIP: Ignore actuator spans

### PR DESCRIPTION
**Pull request by adamleantech**
Related to #1060

### CODE REVIEW

**Comment by adamleantech** [comment]
@trask would appreciate some advice about this PR - functionally it does what I would like as I've tested it against a local service running actuator.  The ActuatorFilteringTracerProviderConfigurer class is just a convenience around the PatternFilteringSampler.  What I'd like help with is whether this approach is the right one, where this code should ideally live and how I might go about testing it

**Comment by trask** [comment]
hi @adamleantech, I think we would prefer to see configurable sampler approach for filtering out health checks

**Comment by adamleantech** [comment]
> hi @adamleantech, I think we would prefer to see configurable sampler approach for filtering out health checks

@trask Could you please elaborate? Is there an existing configurable sampler that I can take inspiration from?

**Comment by breedx-splk** [comment]
Closing a few old/stale draft PRs. Reopen if interested.

**Pull request closed without merging**
